-- Günün sualları sual bankına (tutor_questions) köçürülür — id-lər eynidir (köhnə cavablar etibarlı qalır).
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 't1', id, 'Əsas bucaqlar', 3, '$\sin 30^\circ + \cos 60^\circ$ ifadəsinin qiymətini tapın.', '{"A":"0","B":"$\\frac{1}{2}$","C":"1","D":"$\\frac{\\sqrt{3}}{2}$","E":"$\\sqrt{3}$"}', '2025 toplu, I hissə, səh.92 №1–6', 'C', '', '["$\\sin 30^\\circ = \\frac{1}{2}$, $\\cos 60^\\circ = \\frac{1}{2}$.","Cəm: $\\frac{1}{2} + \\frac{1}{2} =$ **1**."]', 100 FROM topics WHERE slug = 'triqonometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 't2', id, 'Əsas eynilik', 4, '$\sin^2\alpha + \cos^2\alpha$ ifadəsinin qiyməti neçədir?', '{"A":"1","B":"0","C":"2","D":"$\\sin 2\\alpha$","E":"$-1$"}', '2025 toplu, I hissə, səh.94 №2–8', 'A', '', '["Əsas triqonometrik eynilik istənilən $\\alpha$ üçün doğrudur.","$\\sin^2\\alpha + \\cos^2\\alpha =$ **1**."]', 101 FROM topics WHERE slug = 'triqonometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 't3', id, 'Əsas eynilik', 4, '$\sin\alpha = \frac{3}{5}$ və $\alpha$ iti bucaqdır. $\cos\alpha$-nı tapın.', '{"A":"$\\frac{3}{4}$","B":"$\\frac{4}{5}$","C":"$\\frac{3}{5}$","D":"$\\frac{5}{4}$","E":"$\\frac{1}{5}$"}', '2025 toplu, I hissə, səh.94 №2–8', 'B', '', '["$\\cos^2\\alpha = 1 - \\sin^2\\alpha = 1 - \\frac{9}{25} = \\frac{16}{25}$.","$\\alpha$ iti bucaqdır, ona görə $\\cos\\alpha > 0$.","$\\cos\\alpha =$ **$\\frac{4}{5}$**."]', 102 FROM topics WHERE slug = 'triqonometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 't4', id, 'İkiqat bucaq düsturları', 2, '$2\sin 15^\circ \cdot \cos 15^\circ$ ifadəsinin qiymətini tapın.', '{"A":"1","B":"$\\frac{\\sqrt{3}}{2}$","C":"$\\frac{1}{4}$","D":"$\\frac{1}{2}$","E":"$\\frac{\\sqrt{2}}{2}$"}', '2023 toplu, II hissə, səh.88 №3–9', 'D', '', '["$2\\sin x \\cdot \\cos x = \\sin 2x$.","$2\\sin 15^\\circ \\cdot \\cos 15^\\circ = \\sin 30^\\circ =$ **$\\frac{1}{2}$**."]', 103 FROM topics WHERE slug = 'triqonometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 't5', id, 'İkiqat bucaq düsturları', 2, '$\sin\alpha = \frac{1}{2}$ olarsa, $\cos 2\alpha$-nı tapın.', '{"A":"0","B":"$\\frac{1}{4}$","C":"$\\frac{1}{2}$","D":"$\\frac{3}{4}$","E":"1"}', '2023 toplu, II hissə, səh.88 №3–9', 'C', '', '["$\\cos 2\\alpha = 1 - 2\\sin^2\\alpha$.","$1 - 2 \\cdot \\left(\\frac{1}{2}\\right)^2 = 1 - \\frac{1}{2} =$ **$\\frac{1}{2}$**."]', 104 FROM topics WHERE slug = 'triqonometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 't6', id, 'Əsas bucaqlar', 3, '$\operatorname{tg} 45^\circ + \cos 0^\circ$ ifadəsinin qiymətini tapın.', '{"A":"0","B":"1","C":"2","D":"$\\sqrt{2}$","E":"$\\frac{1}{2}$"}', '2025 toplu, I hissə, səh.92 №1–6', 'C', '', '["$\\operatorname{tg} 45^\\circ = 1$, $\\cos 0^\\circ = 1$.","Cəm: $1 + 1 =$ **2**."]', 105 FROM topics WHERE slug = 'triqonometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 't7', id, 'Gətirmə düsturları', 3, '$\sin 150^\circ$ ifadəsinin qiymətini tapın.', '{"A":"$-\\frac{1}{2}$","B":"$\\frac{1}{2}$","C":"$\\frac{\\sqrt{3}}{2}$","D":"$-\\frac{\\sqrt{3}}{2}$","E":"1"}', '2025 toplu, I hissə, səh.97 №1–8', 'B', '', '["$\\sin(180^\\circ - \\alpha) = \\sin\\alpha$.","$\\sin 150^\\circ = \\sin 30^\\circ =$ **$\\frac{1}{2}$**."]', 106 FROM topics WHERE slug = 'triqonometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 't8', id, 'Gətirmə düsturları', 3, '$\cos 120^\circ$ ifadəsinin qiymətini tapın.', '{"A":"$\\frac{1}{2}$","B":"$-\\frac{\\sqrt{3}}{2}$","C":"$-\\frac{1}{2}$","D":"$\\frac{\\sqrt{3}}{2}$","E":"0"}', '2025 toplu, I hissə, səh.97 №1–8', 'C', '', '["$\\cos(180^\\circ - \\alpha) = -\\cos\\alpha$.","$\\cos 120^\\circ = -\\cos 60^\\circ =$ **$-\\frac{1}{2}$**."]', 107 FROM topics WHERE slug = 'triqonometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 't9', id, 'Triqonometrik tənliklər', 2, '$\sin x = 1$ tənliyinin $[0^\circ; 360^\circ)$ aralığındakı həllini tapın.', '{"A":"$0^\\circ$","B":"$45^\\circ$","C":"$90^\\circ$","D":"$180^\\circ$","E":"$270^\\circ$"}', '2023 toplu, II hissə, səh.91 №1–6', 'C', '', '["Vahid çevrədə $\\sin x = 1$ yalnız bir nöqtədə olur.","$x =$ **$90^\\circ$**."]', 108 FROM topics WHERE slug = 'triqonometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 't10', id, 'Əsas eynilik', 4, '$\operatorname{tg}\alpha = 2$ olarsa, $\operatorname{ctg}\alpha$-nı tapın.', '{"A":"2","B":"$-2$","C":"$\\frac{1}{2}$","D":"$-\\frac{1}{2}$","E":"4"}', '2025 toplu, I hissə, səh.94 №2–8', 'C', '', '["$\\operatorname{tg}\\alpha \\cdot \\operatorname{ctg}\\alpha = 1$.","$\\operatorname{ctg}\\alpha = \\frac{1}{2}$, cavab **$\\frac{1}{2}$**."]', 109 FROM topics WHERE slug = 'triqonometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'l1', id, 'Loqarifmin tərifi', 3, '$\log_2 8$ ifadəsinin qiymətini tapın.', '{"A":"2","B":"3","C":"4","D":"8","E":"16"}', '2025 toplu, I hissə, səh.108 №1–5', 'B', '', '["$\\log_2 8 = x \\Leftrightarrow 2^x = 8$.","$2^3 = 8$, deməli $x =$ **3**."]', 110 FROM topics WHERE slug = 'loqarifm-ustlu-tenlik-berabersizlik';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'l2', id, 'Loqarifmin tərifi', 3, '$\log_3 81$ ifadəsinin qiymətini tapın.', '{"A":"3","B":"9","C":"27","D":"4","E":"2"}', '2025 toplu, I hissə, səh.108 №1–5', 'D', '', '["$3^x = 81$.","$3^4 = 81$, deməli cavab **4**."]', 111 FROM topics WHERE slug = 'loqarifm-ustlu-tenlik-berabersizlik';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'l3', id, 'Onluq loqarifm', 1, '$\lg 1000$ ifadəsinin qiymətini tapın.', '{"A":"1","B":"2","C":"3","D":"10","E":"100"}', '2025 toplu, I hissə, səh.110 №7–9', 'C', '', '["$\\lg 1000 = \\log_{10} 1000$.","$10^3 = 1000$, deməli cavab **3**."]', 112 FROM topics WHERE slug = 'loqarifm-ustlu-tenlik-berabersizlik';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'l4', id, 'Loqarifmik tənliklər', 4, '$\log_2 x = 5$ olarsa, $x$-i tapın.', '{"A":"10","B":"25","C":"16","D":"32","E":"64"}', '2025 toplu, I hissə, səh.112 №1–6', 'D', '', '["Tərifə görə $x = 2^5$.","$x =$ **32**."]', 113 FROM topics WHERE slug = 'loqarifm-ustlu-tenlik-berabersizlik';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'l5', id, 'Loqarifmin xassələri', 3, '$\log_6 4 + \log_6 9$ ifadəsinin qiymətini tapın.', '{"A":"1","B":"2","C":"3","D":"13","E":"36"}', '2023 toplu, I hissə, səh.71 №4–10', 'B', '', '["Eyni əsaslı loqarifmlərin cəmi: $\\log_6 (4 \\cdot 9) = \\log_6 36$.","$6^2 = 36$, deməli cavab **2**."]', 114 FROM topics WHERE slug = 'loqarifm-ustlu-tenlik-berabersizlik';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'l6', id, 'Loqarifmin xassələri', 3, '$\log_2 48 - \log_2 3$ ifadəsinin qiymətini tapın.', '{"A":"4","B":"3","C":"16","D":"45","E":"5"}', '2023 toplu, I hissə, səh.71 №4–10', 'A', '', '["Fərq: $\\log_2 \\frac{48}{3} = \\log_2 16$.","$2^4 = 16$, deməli cavab **4**."]', 115 FROM topics WHERE slug = 'loqarifm-ustlu-tenlik-berabersizlik';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'l7', id, 'Loqarifmin tərifi', 3, '$\log_5 \frac{1}{25}$ ifadəsinin qiymətini tapın.', '{"A":"2","B":"$-2$","C":"$\\frac{1}{2}$","D":"$-\\frac{1}{2}$","E":"$-5$"}', '2025 toplu, I hissə, səh.108 №1–5', 'B', '', '["$5^x = \\frac{1}{25} = 5^{-2}$.","$x =$ **$-2$**."]', 116 FROM topics WHERE slug = 'loqarifm-ustlu-tenlik-berabersizlik';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'l8', id, 'Əsas loqarifmik eynilik', 2, '$3^{\log_3 7}$ ifadəsinin qiymətini tapın.', '{"A":"3","B":"7","C":"21","D":"$\\log_3 7$","E":"10"}', '2025 toplu, I hissə, səh.109 №6–10', 'B', '', '["Əsas loqarifmik eynilik: $a^{\\log_a b} = b$.","$3^{\\log_3 7} =$ **7**."]', 117 FROM topics WHERE slug = 'loqarifm-ustlu-tenlik-berabersizlik';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'l9', id, 'Loqarifmik tənliklər', 4, '$\log_3 (x - 2) = 2$ tənliyini həll edin.', '{"A":"8","B":"9","C":"11","D":"6","E":"4"}', '2025 toplu, I hissə, səh.112 №1–6', 'C', '', '["Tərifə görə $x - 2 = 3^2 = 9$.","$x =$ **11** (yoxlama: $x - 2 > 0$)."]', 118 FROM topics WHERE slug = 'loqarifm-ustlu-tenlik-berabersizlik';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'l10', id, 'Üstlü tənliklər', 3, '$2^{x+1} = 16$ tənliyini həll edin.', '{"A":"2","B":"3","C":"4","D":"8","E":"15"}', '2023 toplu, I hissə, səh.75 №1–8', 'B', '', '["$16 = 2^4$, deməli $x + 1 = 4$.","$x =$ **3**."]', 119 FROM topics WHERE slug = 'loqarifm-ustlu-tenlik-berabersizlik';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 's1', id, 'Kub', 5, 'Tili 3 sm olan kubun həcmi neçə sm³-dir?', '{"A":"9","B":"18","C":"27","D":"54","E":"81"}', '2025 toplu, II hissə, səh.201 №1–7', 'C', '', '["Kubun həcmi $V = a^3$.","$V = 3^3 =$ **27 sm³**."]', 120 FROM topics WHERE slug = 'stereometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 's2', id, 'Kub', 5, 'Tili 2 sm olan kubun tam səthinin sahəsi neçə sm²-dir?', '{"A":"8","B":"12","C":"16","D":"24","E":"48"}', '2025 toplu, II hissə, səh.201 №1–7', 'D', '', '["Kubun 6 üzü var, hər birinin sahəsi $a^2$.","$S = 6 \\cdot 2^2 =$ **24 sm²**."]', 121 FROM topics WHERE slug = 'stereometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 's3', id, 'Düzbucaqlı paralelepiped', 4, 'Ölçüləri 2 sm, 3 sm və 4 sm olan düzbucaqlı paralelepipedin həcmi neçə sm³-dir?', '{"A":"24","B":"9","C":"12","D":"20","E":"26"}', '2025 toplu, II hissə, səh.204 №3–9', 'A', '', '["$V = a \\cdot b \\cdot c$.","$V = 2 \\cdot 3 \\cdot 4 =$ **24 sm³**."]', 122 FROM topics WHERE slug = 'stereometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 's4', id, 'Silindr', 3, 'Oturacağının radiusu 3 sm, hündürlüyü 5 sm olan silindrin həcmini tapın.', '{"A":"$15\\pi$","B":"$30\\pi$","C":"$45\\pi$","D":"$75\\pi$","E":"$9\\pi$"}', '2023 toplu, II hissə, səh.176 №2–8', 'C', '', '["Silindrin həcmi $V = \\pi R^2 h$.","$V = \\pi \\cdot 3^2 \\cdot 5 =$ **$45\\pi$ sm³**."]', 123 FROM topics WHERE slug = 'stereometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 's5', id, 'Kürə', 2, 'Radiusu 3 sm olan kürənin həcmini tapın ($V = \frac{4}{3}\pi R^3$).', '{"A":"$12\\pi$","B":"$27\\pi$","C":"$36\\pi$","D":"$108\\pi$","E":"$9\\pi$"}', '2023 toplu, II hissə, səh.182 №1–5', 'C', '', '["$V = \\frac{4}{3}\\pi R^3 = \\frac{4}{3}\\pi \\cdot 27$.","$V =$ **$36\\pi$ sm³**."]', 124 FROM topics WHERE slug = 'stereometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 's6', id, 'Kub', 5, 'Kubun həcmi 64 sm³-dir. Onun tili neçə sm-dir?', '{"A":"4","B":"8","C":"16","D":"6","E":"32"}', '2025 toplu, II hissə, səh.201 №1–7', 'A', '', '["$a^3 = 64$.","$a = \\sqrt[3]{64} =$ **4 sm**."]', 125 FROM topics WHERE slug = 'stereometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 's7', id, 'Konus', 3, 'Oturacağının radiusu 3 sm, hündürlüyü 4 sm olan konusun həcmini tapın.', '{"A":"$12\\pi$","B":"$36\\pi$","C":"$16\\pi$","D":"$9\\pi$","E":"$48\\pi$"}', '2023 toplu, II hissə, səh.179 №1–6', 'A', '', '["Konusun həcmi $V = \\frac{1}{3}\\pi R^2 h$.","$V = \\frac{1}{3}\\pi \\cdot 9 \\cdot 4 =$ **$12\\pi$ sm³**."]', 126 FROM topics WHERE slug = 'stereometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 's8', id, 'Silindr', 3, 'Oturacağının radiusu 2 sm, hündürlüyü 5 sm olan silindrin yan səthinin sahəsini tapın.', '{"A":"$10\\pi$","B":"$20\\pi$","C":"$28\\pi$","D":"$40\\pi$","E":"$14\\pi$"}', '2023 toplu, II hissə, səh.176 №2–8', 'B', '', '["Yan səth: $S = 2\\pi R h$.","$S = 2\\pi \\cdot 2 \\cdot 5 =$ **$20\\pi$ sm²**."]', 127 FROM topics WHERE slug = 'stereometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 's9', id, 'Kürə', 2, 'Radiusu 5 sm olan kürənin səthinin sahəsini tapın ($S = 4\pi R^2$).', '{"A":"$25\\pi$","B":"$50\\pi$","C":"$100\\pi$","D":"$\\frac{500}{3}\\pi$","E":"$20\\pi$"}', '2023 toplu, II hissə, səh.182 №1–5', 'C', '', '["$S = 4\\pi R^2 = 4\\pi \\cdot 25$.","$S =$ **$100\\pi$ sm²**."]', 128 FROM topics WHERE slug = 'stereometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 's10', id, 'Düzbucaqlı paralelepiped', 4, 'Ölçüləri 2 sm, 3 sm və 6 sm olan düzbucaqlı paralelepipedin diaqonalını tapın.', '{"A":"11","B":"7","C":"$\\sqrt{11}$","D":"6","E":"$\\sqrt{13}$"}', '2025 toplu, II hissə, səh.204 №3–9', 'B', '', '["$d = \\sqrt{a^2 + b^2 + c^2}$.","$d = \\sqrt{4 + 9 + 36} = \\sqrt{49} =$ **7 sm**."]', 129 FROM topics WHERE slug = 'stereometriya';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'f1', id, 'Sadə və mürəkkəb faiz', 3, '80 ədədinin 15%-i neçədir?', '{"A":"10","B":"12","C":"14","D":"15","E":"16"}', '2025 toplu, I hissə, səh.140 №1–6', 'B', '', '["15% = 0,15.","$80 \\cdot 0{,}15 =$ **12**."]', 130 FROM topics WHERE slug = 'faiz-nisbet-tenasub';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'f2', id, 'Ardıcıl faiz artımı', 2, 'Malın qiyməti əvvəlcə 45% artırıldı, sonra 20% endirildi. Qiymət ilkin qiymətə nəzərən neçə faiz dəyişdi?', '{"A":"12%","B":"20%","C":"16%","D":"18%","E":"24%"}', '2025 toplu, I hissə, səh.146 №11–15', 'C', '', '["İlk qiymət 100 olsun.","Artım: $100 \\cdot 1{,}45 = 145$.","Azalma: $145 \\cdot 0{,}8 = 116$.","Dəyişiklik: $116 - 100 =$ **16%**."]', 131 FROM topics WHERE slug = 'faiz-nisbet-tenasub';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'f3', id, 'Faizlə müqayisə', 3, 'Qiymət 250 manatdan 200 manata endi. Qiymət neçə faiz azaldı?', '{"A":"15%","B":"20%","C":"25%","D":"30%","E":"50%"}', '2025 toplu, I hissə, səh.143 №4–9', 'B', '', '["Azalma: $250 - 200 = 50$ manat.","$\\frac{50}{250} = 0{,}2 =$ **20%**."]', 132 FROM topics WHERE slug = 'faiz-nisbet-tenasub';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'f4', id, 'Faizlə müqayisə', 3, 'A ədədi B-dən 25% böyükdür. B ədədi A-dan neçə faiz kiçikdir?', '{"A":"15%","B":"20%","C":"25%","D":"30%","E":"75%"}', '2025 toplu, I hissə, səh.143 №4–9', 'B', '', '["$A = 1{,}25 \\cdot B$, deməli $B = \\frac{A}{1{,}25} = 0{,}8 \\cdot A$.","$B$ ədədi $A$-dan **20%** kiçikdir."]', 133 FROM topics WHERE slug = 'faiz-nisbet-tenasub';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'f5', id, 'Sadə və mürəkkəb faiz', 3, '1000 manat illik 10% mürəkkəb faizlə banka qoyuldu. 2 ildən sonra məbləğ neçə manat olar?', '{"A":"1100","B":"1200","C":"1210","D":"1221","E":"1331"}', '2025 toplu, I hissə, səh.140 №1–6', 'C', '', '["Mürəkkəb faiz: $S = 1000 \\cdot 1{,}1^2$.","$S = 1000 \\cdot 1{,}21 =$ **1210 manat**."]', 134 FROM topics WHERE slug = 'faiz-nisbet-tenasub';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'f6', id, 'Faizlə müqayisə', 3, 'Hansı ədədin 30%-i 45-ə bərabərdir?', '{"A":"135","B":"150","C":"15","D":"75","E":"1350"}', '2025 toplu, I hissə, səh.143 №4–9', 'B', '', '["$0{,}3 \\cdot x = 45$.","$x = 45 : 0{,}3 =$ **150**."]', 135 FROM topics WHERE slug = 'faiz-nisbet-tenasub';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'f7', id, 'Nisbət və tənasüb', 4, '$\frac{x}{12} = \frac{5}{4}$ tənasübündən $x$-i tapın.', '{"A":"10","B":"12","C":"15","D":"16","E":"20"}', '2025 toplu, I hissə, səh.136 №1–8', 'C', '', '["Tənasübün əsas xassəsi: $4x = 12 \\cdot 5$.","$x = \\frac{60}{4} =$ **15**."]', 136 FROM topics WHERE slug = 'faiz-nisbet-tenasub';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'f8', id, 'Nisbət və tənasüb', 4, '60 manat iki nəfər arasında 2 : 3 nisbətində bölündü. Çox pay alan neçə manat aldı?', '{"A":"24","B":"30","C":"36","D":"40","E":"20"}', '2025 toplu, I hissə, səh.136 №1–8', 'C', '', '["Cəmi $2 + 3 = 5$ hissə, bir hissə $60 : 5 = 12$ manat.","Böyük pay: $3 \\cdot 12 =$ **36 manat**."]', 137 FROM topics WHERE slug = 'faiz-nisbet-tenasub';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'f9', id, 'Ardıcıl faiz artımı', 2, 'Qiymət əvvəlcə 20% artırıldı, sonra 20% endirildi. Son qiymət ilkin qiymətə nəzərən necə dəyişdi?', '{"A":"Dəyişmədi","B":"4% artdı","C":"4% azaldı","D":"2% azaldı","E":"40% azaldı"}', '2025 toplu, I hissə, səh.146 №11–15', 'C', '', '["İlk qiymət 100 olsun: $100 \\cdot 1{,}2 = 120$.","$120 \\cdot 0{,}8 = 96$.","Qiymət **4% azaldı**."]', 138 FROM topics WHERE slug = 'faiz-nisbet-tenasub';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'f10', id, 'Faizlə müqayisə', 3, 'Məhsulun qiyməti 40 manatdan 50 manata qalxdı. Qiymət neçə faiz artdı?', '{"A":"10%","B":"20%","C":"25%","D":"40%","E":"80%"}', '2025 toplu, I hissə, səh.143 №4–9', 'C', '', '["Artım: $50 - 40 = 10$ manat.","$\\frac{10}{40} = 0{,}25 =$ **25%**."]', 139 FROM topics WHERE slug = 'faiz-nisbet-tenasub';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'fn1', id, 'Funksiyanın qiyməti', 4, '$f(x) = 3x - 1$ olarsa, $f(2)$-ni tapın.', '{"A":"4","B":"5","C":"6","D":"7","E":"1"}', '2025 toplu, I hissə, səh.60 №1–8', 'B', '', '["$x = 2$ qiymətini yerinə yazırıq.","$f(2) = 3 \\cdot 2 - 1 =$ **5**."]', 140 FROM topics WHERE slug = 'funksiya-ve-qrafikler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'fn2', id, 'Funksiyanın qiyməti', 4, '$f(x) = x^2 - 2x$ olarsa, $f(-1)$-i tapın.', '{"A":"$-1$","B":"1","C":"3","D":"$-3$","E":"0"}', '2025 toplu, I hissə, səh.60 №1–8', 'C', '', '["$f(-1) = (-1)^2 - 2 \\cdot (-1)$.","$1 + 2 =$ **3**."]', 141 FROM topics WHERE slug = 'funksiya-ve-qrafikler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'fn3', id, 'Xətti funksiya', 3, '$y = 2x - 4$ düz xəttinin $Oy$ oxu ilə kəsişmə nöqtəsinin ordinatını tapın.', '{"A":"2","B":"$-2$","C":"4","D":"$-4$","E":"0"}', '2023 toplu, I hissə, səh.52 №1–6', 'D', '', '["$Oy$ oxunda $x = 0$.","$y = 2 \\cdot 0 - 4 =$ **$-4$**."]', 142 FROM topics WHERE slug = 'funksiya-ve-qrafikler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'fn4', id, 'Xətti funksiya', 3, '$y = kx + 1$ düz xətti $A(2;\, 7)$ nöqtəsindən keçir. $k$-nı tapın.', '{"A":"2","B":"3","C":"4","D":"6","E":"$\\frac{7}{2}$"}', '2023 toplu, I hissə, səh.52 №1–6', 'B', '', '["Nöqtənin koordinatlarını yazırıq: $7 = 2k + 1$.","$2k = 6$, $k =$ **3**."]', 143 FROM topics WHERE slug = 'funksiya-ve-qrafikler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'fn5', id, 'Kvadrat funksiya', 4, '$y = x^2 - 6x + 8$ parabolasının təpə nöqtəsinin absisini tapın.', '{"A":"$-3$","B":"2","C":"3","D":"4","E":"6"}', '2025 toplu, I hissə, səh.66 №2–10', 'C', '', '["Təpənin absisi $x_0 = -\\frac{b}{2a}$.","$x_0 = \\frac{6}{2} =$ **3**."]', 144 FROM topics WHERE slug = 'funksiya-ve-qrafikler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'fn6', id, 'Kvadrat funksiya', 4, '$y = x^2 - 5x + 6$ funksiyasının sıfırlarının cəmini tapın.', '{"A":"5","B":"$-5$","C":"6","D":"$-6$","E":"1"}', '2025 toplu, I hissə, səh.66 №2–10', 'A', '', '["Viyet teoremi: $x_1 + x_2 = -\\frac{b}{a}$.","$x_1 + x_2 =$ **5** ($x_1 = 2$, $x_2 = 3$)."]', 145 FROM topics WHERE slug = 'funksiya-ve-qrafikler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'fn7', id, 'Təyin oblastı', 2, '$y = \sqrt{x - 3}$ funksiyasının təyin oblastını tapın.', '{"A":"$x > 3$","B":"$x \\ge 3$","C":"$x \\le 3$","D":"$x \\ge 0$","E":"$x \\ne 3$"}', '2025 toplu, I hissə, səh.58 №1–7', 'B', '', '["Kök altındakı ifadə mənfi ola bilməz: $x - 3 \\ge 0$.","Təyin oblastı: **$x \\ge 3$**."]', 146 FROM topics WHERE slug = 'funksiya-ve-qrafikler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'fn8', id, 'Təyin oblastı', 2, '$y = \frac{5}{x + 2}$ funksiyası $x$-in hansı qiymətində təyin olunmayıb?', '{"A":"$-2$","B":"2","C":"0","D":"5","E":"$-5$"}', '2025 toplu, I hissə, səh.58 №1–7', 'A', '', '["Kəsrin məxrəci sıfır ola bilməz: $x + 2 \\ne 0$.","Funksiya **$x = -2$** olduqda təyin olunmayıb."]', 147 FROM topics WHERE slug = 'funksiya-ve-qrafikler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'fn9', id, 'Funksiyanın qiyməti', 4, '$f(x) = 2^x$ olarsa, $f(3) - f(1)$ ifadəsinin qiymətini tapın.', '{"A":"2","B":"4","C":"6","D":"8","E":"10"}', '2025 toplu, I hissə, səh.60 №1–8', 'C', '', '["$f(3) = 2^3 = 8$, $f(1) = 2^1 = 2$.","$8 - 2 =$ **6**."]', 148 FROM topics WHERE slug = 'funksiya-ve-qrafikler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'fn10', id, 'Kvadrat funksiya', 4, '$y = -x^2 + 4x$ funksiyasının ən böyük qiymətini tapın.', '{"A":"2","B":"4","C":"8","D":"0","E":"16"}', '2025 toplu, I hissə, səh.66 №2–10', 'B', '', '["Təpə: $x_0 = -\\frac{4}{2 \\cdot (-1)} = 2$.","$y(2) = -4 + 8 =$ **4**."]', 149 FROM topics WHERE slug = 'funksiya-ve-qrafikler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'u1', id, 'Bucaqların cəmi', 4, 'Üçbucağın iki bucağı 45° və 75°-dir. Üçüncü bucağı tapın.', '{"A":"50°","B":"60°","C":"70°","D":"80°","E":"120°"}', '2025 toplu, II hissə, səh.150 №1–5', 'B', '', '["Üçbucağın bucaqlarının cəmi $180^\\circ$-dir.","$180^\\circ - 45^\\circ - 75^\\circ =$ **$60^\\circ$**."]', 150 FROM topics WHERE slug = 'ucbucaqlar';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'u2', id, 'Bərabəryanlı üçbucaq', 3, 'Bərabəryanlı üçbucağın təpə bucağı 40°-dir. Oturacaq bucağını tapın.', '{"A":"40°","B":"60°","C":"70°","D":"80°","E":"140°"}', '2025 toplu, II hissə, səh.152 №1–6', 'C', '', '["Oturacaq bucaqları bərabərdir: $2x + 40^\\circ = 180^\\circ$.","$x =$ **$70^\\circ$**."]', 151 FROM topics WHERE slug = 'ucbucaqlar';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'u3', id, 'Pifaqor teoremi', 5, 'Katetləri 5 və 12 olan düzbucaqlı üçbucağın hipotenuzunu tapın.', '{"A":"13","B":"17","C":"15","D":"$\\sqrt{119}$","E":"11"}', '2025 toplu, II hissə, səh.154 №2–9', 'A', '', '["$c^2 = 5^2 + 12^2 = 25 + 144 = 169$.","$c =$ **13**."]', 152 FROM topics WHERE slug = 'ucbucaqlar';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'u4', id, 'Pifaqor teoremi', 5, 'Düzbucaqlı üçbucağın hipotenuzu 10, katetlərindən biri 6-dır. Digər kateti tapın.', '{"A":"4","B":"6","C":"8","D":"$2\\sqrt{34}$","E":"16"}', '2025 toplu, II hissə, səh.154 №2–9', 'C', '', '["$b^2 = 10^2 - 6^2 = 100 - 36 = 64$.","$b =$ **8**."]', 153 FROM topics WHERE slug = 'ucbucaqlar';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'u5', id, 'Üçbucağın sahəsi', 4, 'Katetləri 6 və 9 olan düzbucaqlı üçbucağın sahəsini tapın.', '{"A":"15","B":"27","C":"54","D":"30","E":"18"}', '2025 toplu, II hissə, səh.158 №1–6', 'B', '', '["Düzbucaqlı üçbucağın sahəsi: $S = \\frac{1}{2}ab$.","$S = \\frac{1}{2} \\cdot 6 \\cdot 9 =$ **27**."]', 154 FROM topics WHERE slug = 'ucbucaqlar';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'u6', id, 'Üçbucağın sahəsi', 4, 'Üçbucağın iki tərəfi 8 və 5, onlar arasındakı bucaq 30°-dir. Üçbucağın sahəsini tapın.', '{"A":"10","B":"20","C":"40","D":"$10\\sqrt{3}$","E":"13"}', '2025 toplu, II hissə, səh.158 №1–6', 'A', '', '["$S = \\frac{1}{2}ab\\sin\\gamma$.","$S = \\frac{1}{2} \\cdot 8 \\cdot 5 \\cdot \\frac{1}{2} =$ **10**."]', 155 FROM topics WHERE slug = 'ucbucaqlar';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'u7', id, 'Bərabərtərəfli üçbucaq', 3, 'Tərəfi 4 olan bərabərtərəfli üçbucağın hündürlüyünü tapın.', '{"A":"2","B":"$2\\sqrt{2}$","C":"$2\\sqrt{3}$","D":"$4\\sqrt{3}$","E":"$\\sqrt{3}$"}', '2023 toplu, II hissə, səh.127 №1–5', 'C', '', '["Bərabərtərəfli üçbucaqda $h = \\frac{a\\sqrt{3}}{2}$.","$h = \\frac{4\\sqrt{3}}{2} =$ **$2\\sqrt{3}$**."]', 156 FROM topics WHERE slug = 'ucbucaqlar';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'u8', id, 'Orta xətt', 2, 'Üçbucağın bir tərəfi 14-dür. Bu tərəfə paralel orta xəttin uzunluğunu tapın.', '{"A":"7","B":"14","C":"28","D":"3,5","E":"21"}', '2023 toplu, II hissə, səh.129 №2–6', 'A', '', '["Orta xətt paralel tərəfin yarısına bərabərdir.","$14 : 2 =$ **7**."]', 157 FROM topics WHERE slug = 'ucbucaqlar';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'u9', id, 'Kosinuslar teoremi', 3, 'Üçbucağın iki tərəfi 3 və 5, onlar arasındakı bucaq 120°-dir. Üçüncü tərəfi tapın.', '{"A":"7","B":"8","C":"$\\sqrt{19}$","D":"$\\sqrt{34}$","E":"6"}', '2023 toplu, II hissə, səh.131 №1–7', 'A', '', '["$c^2 = a^2 + b^2 - 2ab\\cos\\gamma$.","$c^2 = 9 + 25 - 2 \\cdot 3 \\cdot 5 \\cdot \\left(-\\frac{1}{2}\\right) = 49$.","$c =$ **7**."]', 158 FROM topics WHERE slug = 'ucbucaqlar';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'u10', id, 'Xarici bucaq', 2, 'Üçbucağın xarici bucağı 110°, ona qonşu olmayan daxili bucaqlardan biri 40°-dir. Digər daxili bucağı tapın.', '{"A":"40°","B":"60°","C":"70°","D":"110°","E":"30°"}', '2025 toplu, II hissə, səh.150 №1–5', 'C', '', '["Xarici bucaq ona qonşu olmayan iki daxili bucağın cəminə bərabərdir.","$110^\\circ - 40^\\circ =$ **$70^\\circ$**."]', 159 FROM topics WHERE slug = 'ucbucaqlar';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'a1', id, 'Ədədi silsilə', 4, 'Ədədi silsilədə $a_1 = 5$, $d = 3$. $a_6$-nı tapın.', '{"A":"18","B":"20","C":"23","D":"15","E":"8"}', '2025 toplu, I hissə, səh.120 №1–8', 'B', '', '["$a_n = a_1 + (n - 1)d$.","$a_6 = 5 + 5 \\cdot 3 =$ **20**."]', 160 FROM topics WHERE slug = 'ededi-ardicilliqlar-silsileler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'a2', id, 'Ədədi silsilə', 4, 'Ədədi silsilədə $a_3 = 10$, $a_7 = 22$. Silsilənin fərqini tapın.', '{"A":"2","B":"3","C":"4","D":"6","E":"12"}', '2025 toplu, I hissə, səh.120 №1–8', 'B', '', '["$a_7 - a_3 = 4d$.","$4d = 12$, $d =$ **3**."]', 161 FROM topics WHERE slug = 'ededi-ardicilliqlar-silsileler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'a3', id, 'Ədədi silsilənin cəmi', 3, 'Ədədi silsilədə $a_1 = 2$, $a_{10} = 20$. İlk 10 həddin cəmini tapın.', '{"A":"100","B":"110","C":"120","D":"220","E":"22"}', '2025 toplu, I hissə, səh.122 №1–6', 'B', '', '["$S_n = \\frac{a_1 + a_n}{2} \\cdot n$.","$S_{10} = \\frac{2 + 20}{2} \\cdot 10 =$ **110**."]', 162 FROM topics WHERE slug = 'ededi-ardicilliqlar-silsileler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'a4', id, 'Ədədi silsilənin cəmi', 3, '1-dən 50-yə qədər bütün natural ədədlərin cəmini tapın.', '{"A":"1250","B":"1275","C":"1300","D":"2550","E":"1225"}', '2025 toplu, I hissə, səh.122 №1–6', 'B', '', '["Bu, $a_1 = 1$, $a_{50} = 50$ olan ədədi silsilədir.","$S = \\frac{1 + 50}{2} \\cdot 50 =$ **1275**."]', 163 FROM topics WHERE slug = 'ededi-ardicilliqlar-silsileler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'a5', id, 'Həndəsi silsilə', 3, 'Həndəsi silsilədə $b_1 = 3$, $q = 2$. $b_5$-i tapın.', '{"A":"24","B":"30","C":"48","D":"96","E":"15"}', '2025 toplu, I hissə, səh.124 №1–7', 'C', '', '["$b_n = b_1 \\cdot q^{n-1}$.","$b_5 = 3 \\cdot 2^4 =$ **48**."]', 164 FROM topics WHERE slug = 'ededi-ardicilliqlar-silsileler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'a6', id, 'Həndəsi silsilə', 3, 'Həndəsi silsilə: $81;\ 27;\ 9;\ \ldots$ Silsilənin vuruğunu tapın.', '{"A":"3","B":"$\\frac{1}{3}$","C":"$-3$","D":"$\\frac{1}{9}$","E":"$-\\frac{1}{3}$"}', '2025 toplu, I hissə, səh.124 №1–7', 'B', '', '["$q = \\frac{b_2}{b_1}$.","$q = \\frac{27}{81} =$ **$\\frac{1}{3}$**."]', 165 FROM topics WHERE slug = 'ededi-ardicilliqlar-silsileler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'a7', id, 'Həndəsi silsilənin cəmi', 2, 'Həndəsi silsilədə $b_1 = 1$, $q = 2$. İlk 5 həddin cəmini tapın.', '{"A":"16","B":"31","C":"32","D":"63","E":"15"}', '2023 toplu, I hissə, səh.96 №1–6', 'B', '', '["$S_n = \\frac{b_1(q^n - 1)}{q - 1}$.","$S_5 = \\frac{2^5 - 1}{2 - 1} =$ **31**."]', 166 FROM topics WHERE slug = 'ededi-ardicilliqlar-silsileler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'a8', id, 'Sonsuz azalan həndəsi silsilə', 2, 'Sonsuz azalan həndəsi silsilədə $b_1 = 6$, $q = \frac{1}{2}$. Silsilənin cəmini tapın.', '{"A":"3","B":"6","C":"9","D":"12","E":"24"}', '2023 toplu, I hissə, səh.96 №1–6', 'D', '', '["$S = \\frac{b_1}{1 - q}$.","$S = \\frac{6}{1 - \\frac{1}{2}} =$ **12**."]', 167 FROM topics WHERE slug = 'ededi-ardicilliqlar-silsileler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'a9', id, 'Ədədi silsilə', 4, 'Ədədi silsilədə $a_1 = 40$, $d = -3$. Silsilənin neçənci həddi 1-ə bərabərdir?', '{"A":"12","B":"13","C":"14","D":"15","E":"39"}', '2025 toplu, I hissə, səh.120 №1–8', 'C', '', '["$40 + (n - 1) \\cdot (-3) = 1$.","$n - 1 = 13$, $n =$ **14**."]', 168 FROM topics WHERE slug = 'ededi-ardicilliqlar-silsileler';--> statement-breakpoint
INSERT OR IGNORE INTO tutor_questions (id, topic_id, type, freq, text, options, ref, answer, hint, steps, sort_order) SELECT 'a10', id, 'Ardıcıllığın düsturu', 2, '$a_n = n^2 - 1$ ardıcıllığının 5-ci həddini tapın.', '{"A":"9","B":"24","C":"25","D":"26","E":"16"}', '2025 toplu, I hissə, səh.118 №1–5', 'B', '', '["$n = 5$ yazırıq.","$a_5 = 5^2 - 1 =$ **24**."]', 169 FROM topics WHERE slug = 'ededi-ardicilliqlar-silsileler';
