// Tətbiq daxili ekranların mətnləri (az.ts → az.app).

export const azApp = {
  nav: {
    label: "Tətbiq",
    home: "Əsas",
    today: "Bu gün",
    todayLong: "Günün sualları",
    tutor: "Repetitor",
    tutorLong: "Onlayn repetitor",
    mistakes: "Səhvlərim",
    score: "Bal simulyatoru",
    exams: "Sınaqlar",
    profile: "Profil",
    stats: "Statistika",
    subscription: "Abunə",
    back: "Geri",
    close: "Bağla",
  },
  sub: {
    active: (days: number) => `Aktiv · ${days} gün`,
    activeLong: (days: number) => `Abunə aktiv · ${days} gün qalıb`,
    canceled: (days: number) => `Bitir · ${days} gün`,
    canceledLong: (days: number) => `Abunə ${days} gün sonra bitir`,
    free: "Pulsuz plan",
    endsTitle: (date: string) => `Abunən ${date}-də bitir`,
    endsText: "Avtomatik yenilənmə söndürülüb. Proqresin saxlanacaq.",
    renew: "Yenilə",
  },
  demo: {
    badge: "Demo",
    note: "Bu ekranlar demo məlumatlarla işləyir. Real mövzular və suallar Excel yükləndikdən sonra gələcək.",
    reset: "Demo məlumatlarını sıfırla",
    freePlan: "Pulsuz plan kimi bax",
    freePlanHint: "Abunə olsan da: günün sualları (hər mövzudan 1-dən başqa) və statistikanın ödənişli hissələri kilidlənir.",
    on: "Açıq",
    off: "Bağlı",
  },
  panel: {
    title: "Əsas səhifə",
    hello: (name: string) => `Salam, ${name}!`,
    todaySummary: (topics: number, questions: number) => `Bu gün ${topics} mövzu üzrə ${questions} sual var. Başlayaq?`,
    todaySummaryFree: (open: number, locked: number) =>
      open > 0
        ? `Pulsuz planda bu gün ${open} sual açıqdır, daha ${locked} sual abunə ilə açılır.`
        : `Pulsuz suallar həll olunub. Daha ${locked} sual abunə ilə açılır.`,
    seeAll: "Hamısına bax",
    allDone: "Bu günün bütün sualları həll olunub. Sabah yeniləri gələcək.",
    todayTitle: "Bu günün sualları",
    left: (n: number) => `${n} sual qalıb`,
    todayN: (n: number) => `Bu gün ${n} sual`,
    done: "Tamamlandı",
    typesTitle: "Tiplər üzrə proqres",
    allTopics: "Bütün mövzular",
    streak: "gün ardıcıl",
    record: (n: number) => `Rekord: ${n} gün`,
    continue: "Davam et",
    examInProgress: "Sınaq · yarımçıq",
    examProgress: (done: number, total: number, min: number) => `${done} / ${total} sual · ${min} dəq qalıb · fasilədə`,
    myExams: "Sınaqlarım",
    myExamsSub: (done: number, inProgress: number) => `${done} tamamlanıb · ${inProgress} yarımçıq`,
    store: "Sınaq mağazası",
    storeSub: (names: string) => (names ? `Yeni: ${names}` : "Hamısı alınıb"),
  },
  daily: {
    title: "Günün sualı",
    overviewTitle: "Günün sualları",
    overviewLead: (topics: number, n: number) => `Bu gün ${topics} mövzu üzrə ${n} sual. Hər mövzuda 10 sual.`,
    overviewLeadFree: (free: number, locked: number) =>
      `Pulsuz planda hər mövzudan ${free} sual açıqdır. Qalan ${locked} sual abunə ilə açılır.`,
    continue: "Davam et",
    topicDone: (done: number, total: number) => `${done} / ${total}`,
    topicFree: (open: number, locked: number) => `${open} pulsuz · ${locked} kilidli`,
    freeDone: (locked: number) => `Pulsuz sual həll olunub · ${locked} kilidli`,
    pagerLabel: (topic: string) => `${topic}: suallar`,
    pagerStatus: { ok: "düzgün", bad: "səhv", open: "açıq", locked: "kilidli, abunə ilə" },
    pagerItem: (n: number, status: string) => `Sual ${n}, ${status}`,
    lockedTitle: "Bu sual abunə ilə açılır",
    lockedText: "Pulsuz planda hər mövzudan yalnız 1 sual açıqdır. Abunə ilə hər mövzu üzrə gündə 10 sual, həll izahları və tiplər üzrə proqres.",
    lockedHidden: "Sualın mətni və variantları abunədən sonra görünəcək",
    subscribe: "Abunə ol",
    toFree: "Pulsuz suala keç",
    upsellTitle: "Günün sualları abunə ilə tam açılır",
    upsellText: (locked: number) =>
      `Hər mövzu üzrə gündə 10 sual, hər birinin həll izahı və tiplər üzrə proqres. İndi ${locked} sual kilidlidir.`,
    freeFinishTitle: "Pulsuz suallar bitdi!",
    freeFinishText: "Əla başlanğıc. Qalan suallar və həll izahları abunə ilə açılır.",
    progress: (topic: string) => `${topic} · bu gün`,
    inExam: (n: number) => `İmtahanda: ${n} dəfə`,
    imagePlaceholder: "Şəkil / çertyoj üçün yer (varsa)",
    optionsLabel: "Cavab variantları",
    optionsTitle: "Cavab variantları",
    optionsHint: "— birini seç",
    selectedLabel: "Seçilmiş cavab:",
    selectedNone: "Cavab hələ seçilməyib",
    option: (l: string, v: string) => `Variant ${l}: ${v}`,
    check: "Cavabı yoxla",
    clearSelection: "Seçimi sil",
    dontKnow: "Bilmirəm, həllə bax",
    correct: "Düzgündür!",
    typeStats: (ok: number, total: number) => `Bu tipdə düzgün cavabların: ${ok} / ${total}.`,
    wrong: (l: string) => `Yanlışdır. Düzgün cavab: ${l}`,
    wrongText: "Narahat olma — bu tip üzrə 2 sual da göndərəcəyik.",
    skipped: (l: string) => `Düzgün cavab: ${l}`,
    skippedText: "Həllə bax və bu tipi toplu üzrə işlə.",
    solution: "Qısa həll",
    bookCta: "Bu tipi toplu üzrə işlə",
    next: "Növbəti sual",
    finishTitle: "Bu günün sualları bitdi!",
    finishText: "Əla iş. Sabah seçdiyin mövzular üzrə yeni suallar gələcək.",
    toPanel: "Panelə qayıt",
  },
  score: {
    title: "DİM bal simulyatoru",
    lead: "Hər bölmədə neçə düzgün cavab verəcəyini yaz — təxmini imtahan balını dərhal gör.",
    kindLabel: "İmtahan növü",
    soon: "Tezliklə",
    sections: {
      closed: "Qapalı suallar (A–E)",
      coded: "Kodlaşdırılan suallar",
      written: "Yazılı (açıq) suallar",
    } as Record<string, string>,
    inputLabel: (section: string, max: number) => `${section}: düzgün cavab sayı (0–${max})`,
    correctOf: (max: number) => `/ ${max} düzgün`,
    dec: (section: string) => `${section}: bir az`,
    inc: (section: string) => `${section}: bir çox`,
    points: (n: number) => `${n} bal`,
    resultTitle: "Təxmini bal",
    resultSr: (score: number, max: number) => `Təxmini bal: ${score}, maksimum ${max}`,
    reset: "Sıfırla",
    demoFormula: (p: number) => `Demo hesablama: hər düzgün cavab ${p} bal. Real DİM düsturu sonra əlavə olunacaq.`,
    soonText: "Bu imtahan növü üçün simulyator hazırlanır. Məzmun sonra əlavə olunacaq.",
    infoTitle: "Bal necə hesablanır",
    infoPlaceholder: "[Məzmun sonra əlavə olunacaq: DİM-in bal düsturu, bölmələrin çəkisi, yazılı tapşırıqların qiymətləndirilməsi, keçid balları.]",
    panelText: "Təxmini balını hesabla",
  },
  mistakes: {
    title: "Səhvlərim",
    lead: "Günün suallarında, repetitorda və sınaqlarda səhv etdiyin suallar. Təkrar edəndə həmin suallar və onlara oxşar suallar gəlir.",
    repeat: "Səhvlərimi təkrar et",
    repeatHint: (m: number, s: number) => `${m} səhv${s ? ` + ${s} oxşar sual` : ""}`,
    continue: (done: number, total: number) => `Təkrara davam et · ${done}/${total}`,
    restart: "Yenidən başla",
    statActive: "təkrar gözləyir",
    statFixed: "düzəldilib",
    emptyTitle: "Hələ səhvin yoxdur",
    emptyText: "Günün suallarını, repetitoru və ya sınağı həll et — səhv etdiyin suallar burada toplanacaq.",
    toDaily: "Günün suallarına keç",
    allFixedTitle: "Bütün səhvlər düzəldilib!",
    allFixedText: "Yeni səhvlər olanda burada görünəcək.",
    yourAnswer: "Sənin cavabın",
    correctAnswer: "Düzgün cavab",
    skipped: "cavab verilməyib",
    fixed: "Düzəldildi",
    toSolution: "Suala və həllinə bax",
    where: { daily: "Günün sualı", tutor: "Repetitor", practice: "Təkrar" } as Record<string, string>,
    count: (n: number) => `${n} səhv`,
    freeNote: "Pulsuz planda oxşar suallar yalnız açıq suallardan seçilir. Abunə ilə hər mövzu üzrə daha çox oxşar sual gəlir.",
    // Təkrar seansı
    session: "Səhvlərimi təkrar et",
    pagerLabel: "Təkrar sualları",
    kindMistake: "Səhv etdiyin sual",
    kindSimilar: "Oxşar sual",
    fixedNow: "Bu səhv düzəldildi!",
    correctSimilar: "Düzgündür! Bu tipi artıq bacarırsan.",
    wrongMistake: (l: string) => `Yenə səhv. Düzgün cavab: ${l}`,
    wrongSimilar: (l: string) => `Yanlışdır. Düzgün cavab: ${l}`,
    wrongText: "Həllə diqqətlə bax — bu sual səhvlərində qalır və növbəti təkrarda yenə gələcək.",
    skippedText: "Həllə bax — bu sual növbəti təkrarda yenə gələcək.",
    next: "Növbəti sual",
    finish: "Nəticəyə bax",
    doneTitle: "Təkrar bitdi",
    doneText: (ok: number, total: number, fixed: number) =>
      `${total} sualdan ${ok}-i düzgün. ${fixed} səhv düzəldildi.`,
    panelText: (active: number) => (active ? `${active} səhv təkrar gözləyir` : "Səhv yoxdur"),
    added: "Bu sual Səhvlərim bölməsinə əlavə olundu.",
    open: "Səhvlərimə bax",
  },
  tutor: {
    title: "Onlayn repetitor",
    question: "Repetitor sualı",
    lead: (rate: number) =>
      `Keçmiş DİM imtahanlarının təhlilinə əsasən seçilmiş suallar: təhlilimizə görə bu sual tiplərinin təxminən ${rate}%-i imtahanda çıxır. Hər sualda ipucu və addım-addım izah var.`,
    statQuestions: "sual",
    statTopics: "mövzu",
    statAnswered: "cavablanıb",
    statCorrect: "düzgün",
    continue: "Davam et",
    allDoneTitle: "Bütün suallar həll olunub!",
    allDoneText: "Yeni suallar tezliklə əlavə olunacaq. Səhv etdiyin tipləri toplu üzrə təkrarla.",
    topicCount: (n: number) => `${n} sual`,
    topicProgress: (done: number, total: number, ok: number) => `${done} / ${total} cavablanıb · ${ok} düzgün`,
    pagerLabel: (topic: string) => `${topic}: repetitor sualları`,
    highChance: "Yüksək ehtimal",
    hint: "İpucu",
    hintTitle: "Repetitorun ipucu",
    optionsLabel: "Cavab variantları",
    clearSelection: "Seçimi sil",
    check: "Cavabı yoxla",
    dontKnow: "Bilmirəm, izaha bax",
    correct: "Düzgündür!",
    correctText: (hint: boolean) =>
      hint ? "İpucu ilə həll etdin. Növbəti dəfə ipucusuz yoxla." : "Əla — bu tip imtahanda tez-tez çıxır.",
    wrong: (l: string) => `Yanlışdır. Düzgün cavab: ${l}`,
    wrongText: "Narahat olma — izaha bax və bu tipi toplu üzrə təkrarla.",
    skipped: (l: string) => `Düzgün cavab: ${l}`,
    skippedText: "İzaha bax, sonra bu tipi toplu üzrə işlə.",
    explain: "Repetitorun izahı",
    bookCta: "Bu tipi toplu üzrə işlə",
    topicStats: "Mövzunun statistikası",
    next: "Növbəti sual",
    toOverview: "Repetitora qayıt",
    demoNote: "Suallar hələlik nümunədir. Admin paneli hazır olanda təhlil olunmuş real suallar burada olacaq.",
    lockedTitle: "Onlayn repetitor abunə ilə açılır",
    lockedText: (rate: number) =>
      `Təhlilimizə görə imtahanda çıxma ehtimalı ən yüksək olan suallar — bu tiplərin təxminən ${rate}%-i imtahanda çıxır.`,
    lockedFeatures: (topics: number) => [
      `Ən çox çıxan ${topics} mövzu üzrə seçilmiş suallar`,
      "Hər sual üçün ipucu",
      "Addım-addım izah və toplu istinadı",
      "Mövzular üzrə proqres",
    ],
    lockedTopics: "Repetitorda olan mövzular",
    subscribe: "Abunə ol",
    panelPaid: (done: number, total: number) => `${done} / ${total} sual · imtahanda çıxma ehtimalı yüksək`,
    panelFree: "Abunə ilə açılır",
  },
  store: {
    title: "Sınaq mağazası",
    subtitle: "Hər sınaq ayrıca alınır və hesabında qalır.",
    filters: { all: "Hamısı", owned: "Alınmış", new: "Yeni" },
    questions: (n: number) => `${n} sual`,
    minutes: (n: number) => `${n} dəq`,
    format: (c: number, k: number, w: number) => `${c} qapalı · ${k} kodlaşdırılan · ${w} yazılı`,
    inProgress: "Yarımçıq",
    owned: "Alınıb",
    score: (n: number) => `Bal: ${n}`,
    buy: (price: string) => `Satın al · ${price}`,
    start: "Başla",
    resume: (done: number, total: number) => `Davam et · ${done}/${total}`,
    paused: (min: number) => `Fasilədə · ${min} dəq qalıb`,
    expired: "Vaxt bitib",
    result: "Nəticəyə bax",
    empty: "Bu bölmədə sınaq yoxdur.",
  },
  exam: {
    question: (n: number, total: number) => `Sual ${n} / ${total}`,
    timerLabel: (m: number, s: number) => `Qalan vaxt ${m} dəqiqə ${s} saniyə`,
    warn10: "10 dəqiqə qaldı.",
    warn5: "5 dəqiqə qaldı.",
    formats: { closed: "Qapalı", coded: "Kodlaşdırılan", written: "Yazılı" },
    flag: "İşarələ",
    unflag: "İşarəni götür",
    clearAnswer: "Cavabı sil",
    sheetHint: "Seçilmiş dairəyə yenidən bassanız, cavab silinir.",
    circleLabel: (l: string, on: boolean) => (on ? `${l}, seçilib — silmək üçün yenidən basın` : l),
    imagePlaceholder: "Şəkil / qrafik üçün yer",
    optionsLabel: (n: number) => `Sual ${n} variantları`,
    codedLabel: "Cavabını rəqəmlərlə yaz",
    codedAria: "Cavab, rəqəmlərlə",
    codedHint: (max: number) => `Rəqəm, vergül və mənfi işarəsi. Maks. ${max} simvol.`,
    codedError: (max: number) => `Yalnız rəqəm, bir vergül (,) və əvvəldə mənfi (−) işarəsi. Maks. ${max} simvol.`,
    writtenLabel: "Həllini yaz",
    writtenHint: "Yazılı hissə müəllim tərəfindən yoxlanılır. Mətn bu cihazda saxlanılır.",
    counter: (n: number, max: number) => `${n} / ${max} simvol`,
    saving: "Yadda saxlanılır…",
    saved: "Yadda saxlanıldı ✓",
    questionsBtn: (done: number, total: number) => `Suallar · ${done}/${total}`,
    sheetBtn: "Vərəq",
    prev: "Əvvəlki",
    next: "Növbəti",
    toSheet: "Cavab vərəqinə keç",
    navTitle: "Suallar",
    legend: { current: "Hazırkı", answered: "Cavablanıb", empty: "Boş", flagged: "İşarələnib" },
    navItem: (n: number, answered: boolean, flagged: boolean) =>
      `Sual ${n}, ${answered ? "cavablanıb" : "boş"}${flagged ? ", işarələnib" : ""}`,
    sheet: "Cavab vərəqi",
    sheetRow: (n: number) => `Sual ${n}`,
    answered: (done: number, total: number) => `${done} / ${total} cavablanıb`,
    sections: { closed: "Qapalı", coded: "Kodlaşdırılan", written: "Yazılı" },
    written: "Yazılıb",
    empty: "Boş",
    finish: "Sınağı bitir",
    finishTitle: "Sınağı bitirək?",
    finishText: (empty: number, flagged: number) =>
      `${empty} sual boşdur, ${flagged} sual işarələnib. Sınağı bitirmək istəyirsiniz?`,
    finishConfirm: "Bitir",
    finishCancel: "Davam et",
    timeoutTitle: "Sınaq vaxtı bitdi",
    timeoutText: (n: number) => `Cavabladığın ${n} sual avtomatik göndərildi. Nəticən hazırdır.`,
    toResult: "Nəticəyə bax",
    toPanel: "Panelə qayıt",
    finalizing: "Cavablar göndərilir…",
    pausedNote: "Vaxt yalnız sınaq səhifəsi açıq olanda gedir. Səhifədən çıxsan və ya vərəqi bağlasan, sayğac dayanır.",
    timerPausedTitle: "Vaxt yalnız bu səhifə açıq olanda gedir",
    saveError: "Cavab saxlanmadı. İnterneti yoxla — yenidən cəhd edəcəyik.",
    locked: "Bu sınaq hələ alınmayıb.",
  },
  result: {
    title: "Nəticə",
    heading: (title: string) => `${title} · nəticə`,
    correct: (n: number) => `${n} düzgün`,
    wrong: (n: number) => `${n} yanlış`,
    empty: (n: number) => `${n} boş`,
    pending: (n: number) => `${n} yoxlanılır`,
    provisional: (n: number) => `İlkin bal. Yazılı hissə (${n} sual) müəllim yoxlayandan sonra yenilənəcək.`,
    timedOut: "Vaxt bitdiyi üçün sınaq avtomatik göndərildi.",
    byTopic: "Mövzular üzrə",
    byTopicNote: "Qapalı və kodlaşdırılan suallar üzrə.",
    weakTitle: "Zəif tiplər üçün tövsiyə",
    weakText: "Bu səhifələri işlə — imtahanda ən çox bu tiplər çıxıb.",
    noWeak: "Zəif tip tapılmadı. Belə davam et!",
    solutions: "Həll izahlarına bax",
    newExam: "Yeni sınaq seç",
    solutionsTitle: "Həll izahları",
    yourAnswer: "Sənin cavabın",
    key: "Düzgün cavab",
    sample: "Nümunə cavab",
    noAnswer: "—",
    writtenGiven: "Yazılıb · yoxlanılır",
    statusCorrect: "Düzgün",
    statusWrong: "Yanlış",
    statusEmpty: "Cavab verilməyib",
    scoreSr: (n: number) => `${n} bal 100 baldan`,
    topicRow: (ok: number, total: number, pct: number) => `${ok}/${total} · ${pct}%`,
    questionNo: (n: number) => `Sual ${n}`,
  },
  profile: {
    title: "Profil",
    sections: { profile: "Profil", security: "Təhlükəsizlik", subscription: "Abunə", history: "Ödəniş tarixçəsi" },
    name: "Ad",
    email: "E-poçt",
    gradeExam: "Sinif və imtahan",
    gradeExamValue: (g: number | null, t: string) => `${g ?? "—"} · ${t}`,
    targets: { buraxilis: "Buraxılış", qebul: "Qəbul", both: "Buraxılış və qəbul" } as Record<string, string>,
    guardian: "Valideyn",
    guardianNone: "Əlavə edilməyib",
    guardianAdd: "Valideyn əlavə et",
    receiptSr: "— qəbzə bax",
    changePassword: "Şifrəni dəyiş",
    google: "Google hesabı",
    googleNone: "Bağlı deyil",
    googleSoon: "Tezliklə",
    plan: "Aylıq abunə",
    noSub: "Pulsuz plan",
    noSubText: "Abunə yoxdur. Açıqdır: statistika və hər mövzudan 1 günün sualı.",
    subscribe: "Abunə ol",
    noPayments: "Hələ ödəniş yoxdur.",
    active: "Aktiv",
    canceled: "Ləğv edilib",
    nextPayment: "Növbəti ödəniş",
    accessUntil: "Giriş qalır",
    amount: "Məbləğ",
    method: "Üsul",
    changeMethod: "Üsulu dəyiş",
    cancel: "Abunəni ləğv et",
    resume: "Abunəni bərpa et",
    logout: "Çıxış",
    meta: (username: string | null, grade: number | null, target: string) =>
      [username ? `@${username}` : null, grade ? `${grade}-ci sinif` : null, target].filter(Boolean).join(" · "),
  },
  cancel: {
    title: "Abunəni ləğv edək?",
    text: (date: string) => `Giriş ${date}-ə qədər qalır. Bundan sonra:`,
    lose: "Günün sualları dayanır",
    keep1: "Proqresin və streak tarixçən saxlanır",
    keep2: "Alınmış sınaqlar səndə qalır",
    reason: "Səbəb",
    optional: "(istəyə bağlı)",
    reasons: ["Bahadır", "İmtahan bitdi", "Vaxtım yoxdur", "Digər"],
    stay: "Abunədə qal",
    confirm: "Bəli, ləğv et",
    doneTitle: "Abunə ləğv edildi",
    doneText: (date: string) => `${date}-ə qədər hər şey açıqdır. Təsdiq məktubu poçtuna göndərildi.`,
    toPanel: "Panelə qayıt",
    undo: "Fikrimi dəyişdim — bərpa et",
  },
  payment: {
    title: "Ödəniş",
    selected: "Seçilmiş plan",
    change: "Dəyiş",
    monthly: "Aylıq abunə",
    monthlyNote: "Hər ay avtomatik yenilənir",
    perMonth: (p: string) => `${p} / ay`,
    examNote: "Bir dəfəlik alış, hesabında qalır",
    method: "Ödəniş üsulu",
    methods: [
      { id: "card", title: "Bank kartı", sub: "Visa, Mastercard və yerli kartlar" },
      { id: "local", title: "Yerli ödəniş üsulu", sub: "[Üsul adı — provayder sonra seçiləcək]" },
      { id: "other", title: "Digər üsul", sub: "[Yer tutucu]" },
    ],
    providerPlaceholder: "Ödəniş provayderinin kart forması (iframe / yönləndirmə — yer tutucu)",
    discount: "Endirim",
    total: "Cəmi",
    consentMonthly: "Abunənin hər ay avtomatik yenilənməsi ilə razıyam.",
    consentExam: "Alış şərtləri ilə razıyam.",
    consentRequired: "Davam etmək üçün razılığı təsdiqlə.",
    refund: "Geri qaytarma siyasəti",
    pay: (p: string) => `${p} ödə`,
    safe: "Kart məlumatları bizdə saxlanmır.",
    demoFail: "Demo: uğursuz ödənişi göstər",
    mockNote: "Demo rejimi: real ödəniş yoxdur, düymə ödənişi təqlid edir.",
    okTitle: "Ödəniş uğurludur",
    okTextMonthly: "Abunən aktivdir. Günün sualları artıq hazırdır.",
    okTextExam: "Sınaq hesabına əlavə olundu. İstədiyin vaxt başla.",
    receipt: "Elektron qəbz",
    paid: "Ödənilib",
    receiptNo: "Qəbz №",
    date: "Tarix",
    plan: "Plan",
    period: "Müddət",
    print: "Çap et / PDF",
    toDaily: "Günün suallarına keç",
    toExam: "Sınağa başla",
    copySent: (email: string) => `Qəbzin surəti ${email} ünvanına göndərildi.`,
    failTitle: "Ödəniş keçmədi",
    failText: "Kartdan pul çıxılmayıb. Narahat olma — yenidən cəhd et.",
    failReason: "Səbəb: bank əməliyyatı rədd etdi",
    failHint: "Kartda kifayət qədər vəsait olduğunu və onlayn ödənişin açıq olduğunu yoxla.",
    retry: "Yenidən cəhd et",
    otherMethod: "Başqa üsul seç",
    support: "Problem qalırsa:",
    supportLink: "Telegram-da yaz",
  },
  stats: {
    title: "Statistika",
    h1: "İmtahan statistikası",
    intro:
      "Keçmiş DİM riyaziyyat imtahanlarının sualları mövzulara bölünüb və 2023 / 2025 test topluları ilə tutuşdurulub. Rəqəmlər süzgəcə görə yenilənir.",
    login: "Daxil ol",
    register: "Qeydiyyat",
    filters: {
      label: "Süzgəclər",
      kind: "İmtahan növü",
      kinds: { all: "Hamısı", buraxilis: "Buraxılış", qebul: "Qəbul" },
      group: "Qrup",
      allGroups: "Bütün qruplar",
      groupOpt: (g: string) => `${g} qrup`,
      years: "İllər",
      yearsHint: "Heç biri seçilməyibsə — bütün illər.",
      reset: "Süzgəcləri sıfırla",
      updating: "Yenilənir…",
    },
    cards: {
      questions: "Analiz olunmuş sual",
      exams: "İmtahan",
      topics: "Mövzu",
      match: "Toplu ilə uyğunluq",
      matchSub: (found: string, total: string) => `2025 toplu: ${found} / ${total} tapılıb`,
      matchSub23: (pct: string) => `2023 toplu: ${pct}`,
    },
    ranking: {
      title: "Mövzular reytinqi",
      subtitle: "Ən çox çıxan mövzudan başlayaraq. Mövzuya klikləyin — ətraflı səhifə açılır.",
      summary: (name: string, n: string, pct: string) => `Ən çox çıxan mövzu: ${name}, ${n} sual, ${pct}`,
      value: (n: string, pct: string) => `${n} sual · ${pct}`,
      personal: (pct: string, ok: number, total: number) => `Sənin nəticən: ${pct} (${ok}/${total})`,
      personalNote: "Nöqtə — sənin düzgün cavab faizin (günün sualları və sınaqlar üzrə, 0–100%).",
      caption: "Mövzular üzrə imtahanda çıxan sual sayı",
      colTopic: "Mövzu",
      colCount: "Sual sayı",
      colShare: "Payı",
      colPersonal: "Sənin nəticən",
    },
    perExam: {
      title: "Hər imtahanda neçə tapşırıq",
      titleKind: (k: string) => `Hər ${k} imtahanında neçə tapşırıq`,
      caption: (n: string) => `Mövzu üzrə imtahan başına tapşırıq sayı (${n} imtahan əsasında)`,
      colTopic: "Mövzu",
      colAvg: "Orta",
      colRange: "Ən az – ən çox",
    },
    plan: {
      title: "Prioritet plan",
      badge: "Abunə",
      subtitle: "Əvvəl bunları işlə. Bal = mövzunun imtahanda çıxma payı × (1 − sənin düzgün faizin).",
      noData: "Bir sınaq və ya 10 günün sualı həll et, plan hazırlansın.",
      lockedTitle: "Prioritet plan abunə ilə açılır",
      lockedText: "Sənin nəticələrinə görə ilk 5 mövzu və hər biri üçün toplu səhifələri.",
      subscribe: "Abunə ol",
      loginText: "Planı görmək üçün daxil ol.",
      score: (share: string, pct: string) => `Payı ${share} · sənin nəticən ${pct}`,
      refs: "Toplu səhifələri:",
      noRefs: "Bu mövzu üzrə toplu istinadı yoxdur.",
      more: "Mövzunun bütün istinadları",
    },
    table: { show: "Cədvəl kimi göstər", chart: "Qrafik kimi göstər" },
    empty: { title: "Bu seçim üçün məlumat yoxdur", text: "Süzgəcləri dəyişin və ya sıfırlayın." },
    error: { title: "Statistika yüklənmədi", text: "Bağlantıda problem oldu. Bir az sonra yenidən cəhd edin.", retry: "Yenidən cəhd et" },
    method: { title: "Metodika və qeydlər" },
    detail: {
      back: "Bütün mövzular",
      cards: { total: "Cəmi sual", share: "Bütün sualların payı", avg: "İmtahan başına orta", match: "Toplu ilə uyğunluq" },
      matchSub: (pct23: string) => `2025 toplu · 2023: ${pct23}`,
      years: "İllər üzrə dinamika",
      yearsSummary: (pairs: string) => `İllər üzrə sual sayı: ${pairs}`,
      yearsCaption: "İllər üzrə sual sayı",
      kinds: "Buraxılış və qəbul",
      kindsSummary: (b: string, q: string) => `Buraxılış: ${b} sual, qəbul: ${q} sual`,
      kindsCaption: "İmtahan növü üzrə sual sayı",
      kind: { buraxilis: "Buraxılış", qebul: "Qəbul" },
      matches: "Uyğunluq dərəcələri",
      matchesSummary: (toplu: string, pairs: string) => `${toplu} toplu: ${pairs}`,
      matchesCaption: (toplu: string) => `${toplu} toplu ilə uyğunluq dərəcələri`,
      toplu: (y: string) => `${y} toplu`,
      colLevel: "Dərəcə",
      colCount: "Sual sayı",
      colYear: "İl",
      colKind: "Növ",
      types: "Sual tipləri",
      typesMore: (n: number) => `Bütün tiplər (${n})`,
      colType: "Tip",
      refs: "Toplu istinadları",
      refsNote: "Yalnız istinad: kitab, hissə, səhifə və nömrə. Sualın mətni göstərilmir.",
      refsLocked: (shown: number, total: number) => `${shown} / ${total} istinad göstərilir. Tam siyahı abunə ilə açılır.`,
      refsCaption: "Toplu istinadları",
      colExam: "İmtahan",
      colNo: "Sual №",
      col2023: "2023 toplu",
      col2025: "2025 toplu",
      none: "—",
    },
  },
} as const;
