// Tətbiq daxili ekranların mətnləri (az.ts → az.app).

export const azApp = {
  nav: {
    label: "Tətbiq",
    home: "Əsas",
    today: "Bu gün",
    todayLong: "Günün sualları",
    tutor: "Repetitor",
    tutorLong: "Onlayn repetitor",
    mistakes: "Səhvlərim",
    score: "Bal simulyatoru",
    exams: "Sınaqlar",
    profile: "Profil",
    stats: "Statistika",
    subscription: "Abunə",
    plans: "Abunəliklər",
    back: "Geri",
    close: "Bağla",
  },
  sub: {
    active: (days: number) => `Aktiv · ${days} gün`,
    activeLong: (days: number, plan = "Abunə") => `${plan} · aktiv · ${days} gün qalıb`,
    canceled: (days: number) => `Bitir · ${days} gün`,
    canceledLong: (days: number, plan = "Abunə") => `${plan} · ${days} gün sonra bitir`,
    free: "Free plan",
    endsTitle: (date: string) => `Abunən ${date}-də bitir`,
    endsText: "Avtomatik yenilənmə söndürülüb. Proqresin saxlanacaq.",
    renew: "Yenilə",
  },
  demo: {
    badge: "Demo",
    note: "Bu ekranlar demo məlumatlarla işləyir. Real mövzular və suallar Excel yükləndikdən sonra gələcək.",
    reset: "Demo məlumatlarını sıfırla",
  },
  panel: {
    title: "Əsas səhifə",
    hello: (name: string) => `Salam, ${name}!`,
    todaySummary: (topics: number, questions: number) => `Bu gün ${topics} mövzu üzrə ${questions} sual var. Başlayaq?`,
    todaySummaryFree: (open: number, locked: number) =>
      open > 0
        ? `Free planda bu gün ${open} sual açıqdır, daha ${locked} sual Pro planı ilə açılır.`
        : `Açıq suallar həll olunub. Daha ${locked} sual Pro planı ilə açılır.`,
    seeAll: "Hamısına bax",
    allDone: "Bu günün bütün sualları həll olunub. Sabah yeniləri gələcək.",
    todayTitle: "Bu günün sualları",
    left: (n: number) => `${n} sual qalıb`,
    todayN: (n: number) => `Bu gün ${n} sual`,
    done: "Tamamlandı",
    typesTitle: "Tiplər üzrə proqres",
    allTopics: "Bütün mövzular",
    streak: "gün ardıcıl",
    record: (n: number) => `Rekord: ${n} gün`,
    continue: "Davam et",
    examInProgress: "Sınaq · yarımçıq",
    examProgress: (done: number, total: number, min: number) => `${done} / ${total} sual · ${min} dəq qalıb · fasilədə`,
    myExams: "Sınaqlarım",
    myExamsSub: (done: number, inProgress: number) => `${done} tamamlanıb · ${inProgress} yarımçıq`,
    store: "Sınaq mağazası",
    storeSub: (names: string) => (names ? `Yeni: ${names}` : "Hamısı alınıb"),
  },
  daily: {
    title: "Günün sualı",
    overviewTitle: "Günün sualları",
    overviewLead: (topics: number, n: number) => `Bu gün sual bankından təsadüfi ${topics} mövzu üzrə ${n} sual. Sabah yeni mövzular gələcək.`,
    overviewLeadFree: (free: number, locked: number) =>
      `Free planda hər mövzudan ${free} sual açıqdır. Qalan ${locked} sual Pro planı ilə açılır.`,
    continue: "Davam et",
    topicDone: (done: number, total: number) => `${done} / ${total}`,
    topicFree: (open: number, locked: number) => `${open} açıq · ${locked} kilidli`,
    freeDone: (locked: number) => `Açıq suallar həll olunub · ${locked} kilidli`,
    pagerLabel: (topic: string) => `${topic}: suallar`,
    pagerStatus: { ok: "düzgün", bad: "səhv", open: "açıq", locked: "kilidli, Pro planı ilə" },
    pagerItem: (n: number, status: string) => `Sual ${n}, ${status}`,
    lockedTitle: "Bu sual Pro planı ilə açılır",
    lockedText: "Free planda günün hər mövzusundan 2 sual açıqdır. Pro planı ilə günün bütün sualları, həll izahları və tiplər üzrə proqres.",
    lockedHidden: "Sualın mətni və variantları Pro planından sonra görünəcək",
    subscribe: "Pro planına keç",
    toFree: "Açıq suala keç",
    upsellTitle: "Günün sualları Pro planı ilə tam açılır",
    upsellText: (locked: number) =>
      `Pro — aylıq 6.90 AZN: günün bütün sualları, həftədə 1 sınaq. İndi ${locked} sual kilidlidir.`,
    freeFinishTitle: "Açıq suallar bitdi!",
    freeFinishText: "Əla başlanğıc. Qalan suallar Pro planı ilə açılır. Sabah yeni suallar gələcək.",
    progress: (topic: string) => `${topic} · bu gün`,
    inExam: (n: number) => `İmtahanda: ${n} dəfə`,
    imagePlaceholder: "Şəkil / çertyoj üçün yer (varsa)",
    optionsLabel: "Cavab variantları",
    optionsTitle: "Cavab variantları",
    optionsHint: "— birini seç",
    selectedLabel: "Seçilmiş cavab:",
    selectedNone: "Cavab hələ seçilməyib",
    option: (l: string, v: string) => `Variant ${l}: ${v}`,
    check: "Cavabı yoxla",
    clearSelection: "Seçimi sil",
    dontKnow: "Bilmirəm, həllə bax",
    correct: "Düzgündür!",
    typeStats: (ok: number, total: number) => `Bu tipdə düzgün cavabların: ${ok} / ${total}.`,
    wrong: (l: string) => `Yanlışdır. Düzgün cavab: ${l}`,
    wrongText: "Narahat olma — bu tip üzrə 2 sual da göndərəcəyik.",
    skipped: (l: string) => `Düzgün cavab: ${l}`,
    skippedText: "Həllə bax və bu tipi toplu üzrə işlə.",
    solution: "Qısa həll",
    bookCta: "Bu tipi toplu üzrə işlə",
    next: "Növbəti sual",
    finishTitle: "Bu günün sualları bitdi!",
    finishText: "Əla iş. Sabah yeni mövzular üzrə suallar gələcək.",
    toPanel: "Panelə qayıt",
  },
  score: {
    title: "DİM bal simulyatoru",
    lead: "Həll etdiyin bütün suallara görə imtahanda təxminən neçə düzgün cavab yazacağını göstəririk. Təxmin üçün ən azı 4 fərqli mövzudan 20 sual həll etməlisən.",
    weekTitle: "Sənin nəticən",
    weekTopics: "fərqli mövzu",
    notReadyTitle: "Təxmin üçün hələ az məlumat var",
    notReadyText: (minQ: number, minT: number) => `Ən azı ${minT} fərqli mövzudan ${minQ} sual həll et — təxmin burada görünəcək.`,
    progressQuestions: (n: number, min: number) => `Sual: ${Math.min(n, min)} / ${min}`,
    progressTopics: (n: number, min: number) => `Mövzu: ${Math.min(n, min)} / ${min}`,
    weekSolved: "həll etdiyin sual",
    weekCorrect: "düzgün cavab",
    weekPct: "düzgün cavab faizi",
    estimateTitle: "Təxmini düzgün cavab sayı",
    estimateBuraxilis: "Buraxılış imtahanı",
    estimateBlok: "Blok imtahanı",
    estimateOf: (max: number) => `/ ${max} sual`,
    estimateFormula: (n: number, pct: string, res: number) => `int(${n} × ${pct} / 100) − 1 = ${res}`,
    infoTitle: "Bal necə hesablanır",
    infoPlaceholder: "[Məzmun sonra əlavə olunacaq: DİM-in bal düsturu, bölmələrin çəkisi, yazılı tapşırıqların qiymətləndirilməsi, keçid balları.]",
    panelText: "Təxmini balını hesabla",
  },
  mistakes: {
    title: "Səhvlərim",
    lead: "Günün suallarında, repetitorda və sınaqlarda səhv etdiyin suallar. Təkrar edəndə həmin suallar və onlara oxşar suallar gəlir.",
    repeat: "Səhvlərimi təkrar et",
    repeatHint: (m: number, s: number) => `${m} səhv${s ? ` + ${s} oxşar sual` : ""}`,
    continue: (done: number, total: number) => `Təkrara davam et · ${done}/${total}`,
    restart: "Yenidən başla",
    statActive: "təkrar gözləyir",
    statFixed: "düzəldilib",
    emptyTitle: "Hələ səhvin yoxdur",
    emptyText: "Günün suallarını, repetitoru və ya sınağı həll et — səhv etdiyin suallar burada toplanacaq.",
    toDaily: "Günün suallarına keç",
    allFixedTitle: "Bütün səhvlər düzəldilib!",
    allFixedText: "Yeni səhvlər olanda burada görünəcək.",
    yourAnswer: "Sənin cavabın",
    correctAnswer: "Düzgün cavab",
    skipped: "cavab verilməyib",
    fixed: "Düzəldildi",
    toSolution: "Suala və həllinə bax",
    where: { daily: "Günün sualı", tutor: "Repetitor", practice: "Təkrar" } as Record<string, string>,
    count: (n: number) => `${n} səhv`,
    freeNote: "Free planda təkrar yalnız öz səhvlərindən ibarətdir. Pro planı ilə hər səhvə 2 oxşar sual da gəlir.",
    // Təkrar seansı
    session: "Səhvlərimi təkrar et",
    pagerLabel: "Təkrar sualları",
    kindMistake: "Səhv etdiyin sual",
    kindSimilar: "Oxşar sual",
    fixedNow: "Bu səhv düzəldildi!",
    correctSimilar: "Düzgündür! Bu tipi artıq bacarırsan.",
    wrongMistake: (l: string) => `Yenə səhv. Düzgün cavab: ${l}`,
    wrongSimilar: (l: string) => `Yanlışdır. Düzgün cavab: ${l}`,
    wrongText: "Həllə diqqətlə bax — bu sual səhvlərində qalır və növbəti təkrarda yenə gələcək.",
    skippedText: "Həllə bax — bu sual növbəti təkrarda yenə gələcək.",
    next: "Növbəti sual",
    finish: "Nəticəyə bax",
    doneTitle: "Təkrar bitdi",
    doneText: (ok: number, total: number, fixed: number) =>
      `${total} sualdan ${ok}-i düzgün. ${fixed} səhv düzəldildi.`,
    panelText: (active: number) => (active ? `${active} səhv təkrar gözləyir` : "Səhv yoxdur"),
    added: "Bu sual Səhvlərim bölməsinə əlavə olundu.",
    open: "Səhvlərimə bax",
  },
  tutor: {
    title: "Onlayn repetitor",
    question: "Repetitor sualı",
    lead: (rate: number) =>
      `Keçmiş DİM imtahanlarının təhlilinə əsasən seçilmiş suallar: təhlilimizə görə bu sual tiplərinin təxminən ${rate}%-i imtahanda çıxır. Hər sualda ipucu və addım-addım izah var.`,
    statQuestions: "sual",
    statTopics: "mövzu",
    statAnswered: "cavablanıb",
    statCorrect: "düzgün",
    continue: "Davam et",
    allDoneTitle: "Bütün suallar həll olunub!",
    allDoneText: "Yeni suallar tezliklə əlavə olunacaq. Səhv etdiyin tipləri toplu üzrə təkrarla.",
    topicCount: (n: number) => `${n} sual`,
    topicProgress: (done: number, total: number, ok: number) => `${done} / ${total} cavablanıb · ${ok} düzgün`,
    pagerLabel: (topic: string) => `${topic}: repetitor sualları`,
    highChance: "Yüksək ehtimal",
    hint: "İpucu",
    hintTitle: "Repetitorun ipucu",
    optionsLabel: "Cavab variantları",
    clearSelection: "Seçimi sil",
    check: "Cavabı yoxla",
    dontKnow: "Bilmirəm, izaha bax",
    correct: "Düzgündür!",
    correctText: (hint: boolean) =>
      hint ? "İpucu ilə həll etdin. Növbəti dəfə ipucusuz yoxla." : "Əla — bu tip imtahanda tez-tez çıxır.",
    wrong: (l: string) => `Yanlışdır. Düzgün cavab: ${l}`,
    wrongText: "Narahat olma — izaha bax və bu tipi toplu üzrə təkrarla.",
    skipped: (l: string) => `Düzgün cavab: ${l}`,
    skippedText: "İzaha bax, sonra bu tipi toplu üzrə işlə.",
    explain: "Repetitorun izahı",
    bookCta: "Bu tipi toplu üzrə işlə",
    topicStats: "Mövzunun statistikası",
    next: "Növbəti sual",
    toOverview: "Repetitora qayıt",
    demoNote: "Suallar hələlik nümunədir. Admin paneli hazır olanda təhlil olunmuş real suallar burada olacaq.",
    lockedTitle: "Onlayn repetitor Premium planı ilə açılır",
    lockedText: (rate: number) =>
      `Təhlilimizə görə imtahanda çıxma ehtimalı ən yüksək olan suallar — bu tiplərin təxminən ${rate}%-i imtahanda çıxır.`,
    lockedFeatures: (topics: number) => [
      `Bütün ${topics} mövzu: nəzəriyyə və praktiki testlər`,
      "Həftəlik qrafik — dərs günlərini özün seçirsən",
      "Hər 2 mövzudan sonra 20 suallıq sınaq",
      "Hər sual üçün ipucu, addım-addım izah və toplu istinadı",
    ],
    lockedTopics: "Repetitorda olan mövzular",
    subscribe: "Premium planına keç",
    panelPaid: (done: number, total: number) => `${done} / ${total} sual · imtahanda çıxma ehtimalı yüksək`,
    // Həftəlik qrafik (Pro)
    weekdays: ["Bazar ertəsi", "Çərşənbə axşamı", "Çərşənbə", "Cümə axşamı", "Cümə", "Şənbə", "Bazar"],
    weekdaysShort: ["B.e.", "Ç.a.", "Ç.", "C.a.", "C.", "Ş.", "B."],
    planTitle: "Həftəlik qrafikini seç",
    planText:
      "Seçdiyin günlərdə mövzular 1-cidən başlayaraq sıra ilə açılacaq: əvvəl nəzəriyyə, sonra praktiki testlər. Hər 2 mövzu bitəndən sonra həmin mövzulardan 20 suallıq sınaq açılır.",
    planDaysLabel: "Dərs günləri",
    planSuggest: "Məsələn: həftənin 2-ci və 4-cü günləri",
    planEmpty: "Ən azı bir gün seç.",
    planSave: "Qrafiki təsdiqlə",
    planChange: "Qrafiki dəyiş",
    planChangeNote: "Artıq açılmış dərslər açıq qalır, qalanları yeni günlərə düşür.",
    planSummary: (days: string) => `Dərs günləri: ${days}`,
    planNext: (date: string) => `Növbəti dərs: ${date}`,
    planAllOpen: "Bütün dərslər açılıb",
    planProgress: (done: number, total: number) => `${done} / ${total} mövzu bitib`,
    curriculumTitle: "Plan",
    lessonPart: (part: number, parts: number) => `${part}-ci hissə / ${parts}`,
    lessonDone: "Bitib",
    lessonOpen: "Açıqdır",
    lessonLocked: (date: string | null) => (date ? `${date} açılacaq` : "Bağlıdır"),
    lessonQuestions: (done: number, total: number) => `${done} / ${total} test`,
    lessonStart: "Dərsə başla",
    lessonContinue: "Davam et",
    lessonReview: "Bax",
    examTitle: (n: number) => `Sınaq ${n}`,
    examOf: (a: string, b: string) => `${a} + ${b}`,
    examQuestions: (n: number) => `${n} sual`,
    examLocked: "Hər iki mövzu bitəndən sonra açılır",
    examOpen: "Sınaq hazırdır",
    examStart: "Sınağa başla",
    examResult: (ok: number, total: number) => `Nəticə: ${ok} / ${total}`,
    examSubmit: "Sınağı bitir",
    examIntro: (n: number) => `${n} sual. Cavablarını seç və sonda "Sınağı bitir" düyməsini bas. Cavabsız suallar səhv sayılır.`,
    examDoneTitle: "Sınaq bitdi",
    examCorrect: "Düzgün",
    examWrong: (l: string) => `Səhv · düzgün cavab: ${l}`,
    examEmpty: (l: string) => `Cavab verilməyib · düzgün cavab: ${l}`,
    examYour: (l: string) => `Sənin cavabın: ${l}`,
    examBack: "Plana qayıt",
    theoryTitle: "Nəzəriyyə",
    theoryEmpty: "Bu mövzunun nəzəriyyəsi tezliklə əlavə olunacaq.",
    practiceTitle: "Praktiki testlər",
    topicLocked: (date: string | null) =>
      date ? `Bu mövzu qrafikinə görə ${date} tarixində açılacaq.` : "Bu mövzu hələ açılmayıb.",
    noPlanLocked: "Əvvəlcə həftəlik qrafikini seç.",
    soonTitle: "Tezliklə",
    soonText: "Bu mövzular üzrə suallar hazırlanır — əlavə olunanda plana avtomatik düşəcək.",
    topicDone: "Mövzu bitib",
    allTopicsTitle: "Bütün mövzular",
    panelFree: "Premium ilə açılır",
  },
  store: {
    title: "Sınaq mağazası",
    subtitle: "Planına görə sınağı özün seçirsən: Free — ayda 1, Pro — həftədə 1, Premium — bütün sınaqlar. Seçdiyin sınaq hesabında qalır.",
    filters: { all: "Hamısı", owned: "Açıq", new: "Yeni" },
    quotaAll: "Premium: bütün sınaqlar açıqdır.",
    quotaLeft: (period: "month" | "week") =>
      period === "month" ? "Bu ay 1 pulsuz sınaq seçə bilərsən." : "Bu həftə 1 sınaq seçə bilərsən.",
    quotaUsed: (period: "month" | "week", date: string) =>
      `${period === "month" ? "Bu ayın" : "Bu həftənin"} sınağını seçmisən. Növbəti seçim: ${date}.`,
    quotaUpgrade: (period: "month" | "week") =>
      period === "month" ? "Pro — həftədə 1 sınaq, Premium — hamısı." : "Premium planında bütün sınaqlar açıqdır.",
    upgrade: "Planları gör",
    claim: (period: "month" | "week") => (period === "month" ? "Bu ayın sınağı kimi seç" : "Bu həftənin sınağı kimi seç"),
    quotaEmpty: "Bu dövrün sınağı artıq seçilib.",
    questions: (n: number) => `${n} sual`,
    minutes: (n: number) => `${n} dəq`,
    format: (c: number, k: number, w: number) => `${c} qapalı · ${k} kodlaşdırılan · ${w} yazılı`,
    inProgress: "Yarımçıq",
    owned: "Alınıb",
    score: (n: number) => `Bal: ${n}`,
    buy: (price: string) => `Satın al · ${price}`,
    start: "Başla",
    resume: (done: number, total: number) => `Davam et · ${done}/${total}`,
    paused: (min: number) => `Fasilədə · ${min} dəq qalıb`,
    expired: "Vaxt bitib",
    result: "Nəticəyə bax",
    empty: "Bu bölmədə sınaq yoxdur.",
  },
  exam: {
    question: (n: number, total: number) => `Sual ${n} / ${total}`,
    timerLabel: (m: number, s: number) => `Qalan vaxt ${m} dəqiqə ${s} saniyə`,
    warn10: "10 dəqiqə qaldı.",
    warn5: "5 dəqiqə qaldı.",
    formats: { closed: "Qapalı", coded: "Kodlaşdırılan", written: "Yazılı" },
    flag: "İşarələ",
    unflag: "İşarəni götür",
    clearAnswer: "Cavabı sil",
    sheetHint: "Seçilmiş dairəyə yenidən bassanız, cavab silinir.",
    circleLabel: (l: string, on: boolean) => (on ? `${l}, seçilib — silmək üçün yenidən basın` : l),
    imagePlaceholder: "Şəkil / qrafik üçün yer",
    optionsLabel: (n: number) => `Sual ${n} variantları`,
    codedLabel: "Cavabını rəqəmlərlə yaz",
    codedAria: "Cavab, rəqəmlərlə",
    codedHint: (max: number) => `Rəqəm, vergül və mənfi işarəsi. Maks. ${max} simvol.`,
    codedError: (max: number) => `Yalnız rəqəm, bir vergül (,) və əvvəldə mənfi (−) işarəsi. Maks. ${max} simvol.`,
    writtenLabel: "Həllini yaz",
    writtenHint: "Yazılı hissə müəllim tərəfindən yoxlanılır. Mətn bu cihazda saxlanılır.",
    counter: (n: number, max: number) => `${n} / ${max} simvol`,
    saving: "Yadda saxlanılır…",
    saved: "Yadda saxlanıldı ✓",
    questionsBtn: (done: number, total: number) => `Suallar · ${done}/${total}`,
    sheetBtn: "Vərəq",
    prev: "Əvvəlki",
    next: "Növbəti",
    toSheet: "Cavab vərəqinə keç",
    navTitle: "Suallar",
    legend: { current: "Hazırkı", answered: "Cavablanıb", empty: "Boş", flagged: "İşarələnib" },
    navItem: (n: number, answered: boolean, flagged: boolean) =>
      `Sual ${n}, ${answered ? "cavablanıb" : "boş"}${flagged ? ", işarələnib" : ""}`,
    sheet: "Cavab vərəqi",
    sheetRow: (n: number) => `Sual ${n}`,
    answered: (done: number, total: number) => `${done} / ${total} cavablanıb`,
    sections: { closed: "Qapalı", coded: "Kodlaşdırılan", written: "Yazılı" },
    written: "Yazılıb",
    empty: "Boş",
    finish: "Sınağı bitir",
    finishTitle: "Sınağı bitirək?",
    finishText: (empty: number, flagged: number) =>
      `${empty} sual boşdur, ${flagged} sual işarələnib. Sınağı bitirmək istəyirsiniz?`,
    finishConfirm: "Bitir",
    finishCancel: "Davam et",
    timeoutTitle: "Sınaq vaxtı bitdi",
    timeoutText: (n: number) => `Cavabladığın ${n} sual avtomatik göndərildi. Nəticən hazırdır.`,
    toResult: "Nəticəyə bax",
    toPanel: "Panelə qayıt",
    finalizing: "Cavablar göndərilir…",
    pausedNote: "Vaxt yalnız sınaq səhifəsi açıq olanda gedir. Səhifədən çıxsan və ya vərəqi bağlasan, sayğac dayanır.",
    timerPausedTitle: "Vaxt yalnız bu səhifə açıq olanda gedir",
    saveError: "Cavab saxlanmadı. İnterneti yoxla — yenidən cəhd edəcəyik.",
    locked: "Bu sınaq hələ alınmayıb.",
  },
  result: {
    title: "Nəticə",
    heading: (title: string) => `${title} · nəticə`,
    correct: (n: number) => `${n} düzgün`,
    wrong: (n: number) => `${n} yanlış`,
    empty: (n: number) => `${n} boş`,
    pending: (n: number) => `${n} yoxlanılır`,
    provisional: (n: number) => `İlkin bal. Yazılı hissə (${n} sual) müəllim yoxlayandan sonra yenilənəcək.`,
    timedOut: "Vaxt bitdiyi üçün sınaq avtomatik göndərildi.",
    byTopic: "Mövzular üzrə",
    byTopicNote: "Qapalı və kodlaşdırılan suallar üzrə.",
    weakTitle: "Zəif tiplər üçün tövsiyə",
    weakText: "Bu səhifələri işlə — imtahanda ən çox bu tiplər çıxıb.",
    noWeak: "Zəif tip tapılmadı. Belə davam et!",
    solutions: "Həll izahlarına bax",
    newExam: "Yeni sınaq seç",
    solutionsTitle: "Həll izahları",
    yourAnswer: "Sənin cavabın",
    key: "Düzgün cavab",
    sample: "Nümunə cavab",
    noAnswer: "—",
    writtenGiven: "Yazılıb · yoxlanılır",
    statusCorrect: "Düzgün",
    statusWrong: "Yanlış",
    statusEmpty: "Cavab verilməyib",
    scoreSr: (n: number) => `${n} bal 100 baldan`,
    topicRow: (ok: number, total: number, pct: number) => `${ok}/${total} · ${pct}%`,
    questionNo: (n: number) => `Sual ${n}`,
  },
  profile: {
    title: "Profil",
    sections: { profile: "Profil", security: "Təhlükəsizlik", subscription: "Abunə", history: "Ödəniş tarixçəsi" },
    name: "Ad",
    email: "E-poçt",
    gradeExam: "Sinif və imtahan",
    gradeExamValue: (g: number | null, t: string) => `${g ?? "—"} · ${t}`,
    targets: { buraxilis: "Buraxılış", qebul: "Qəbul", both: "Buraxılış və qəbul" } as Record<string, string>,
    guardian: "Valideyn",
    guardianNone: "Əlavə edilməyib",
    guardianAdd: "Valideyn əlavə et",
    receiptSr: "— qəbzə bax",
    changePassword: "Şifrəni dəyiş",
    google: "Google hesabı",
    googleNone: "Bağlı deyil",
    contacts: "Əlaqə məlumatları (istəyə bağlı)",
    emailLabel: "E-poçt",
    emailHint: "Təsdiq kodu bu ünvana göndəriləcək. Şifrə bərpası üçün lazımdır.",
    emailVerified: "Təsdiqlənib",
    emailUnverified: "Təsdiqlənməyib",
    emailDone: "E-poçt təsdiqləndi və hesabına əlavə olundu.",
    change: "Dəyiş",
    cancelEdit: "Ləğv et",
    sendCode: "Kod göndər",
    codeSentTo: (email: string) => `${email} ünvanına 6 rəqəmli kod göndərdik. Kod 10 dəqiqə işləyir.`,
    codeLabel: "Təsdiq kodu",
    confirmCode: "Təsdiqlə",
    resendCode: "Kodu yenidən göndər",
    resendIn: (s: number) => `Yenidən göndər · ${s} san`,
    phoneLabel: "Telefon nömrəsi",
    phoneHint: "+994 ilə, məs.: +994 50 123 45 67. Silmək üçün boş saxla.",
    savePhone: "Saxla",
    phoneSaved: "Saxlanıldı ✓",
    googleLinked: "Bağlıdır",
    googleNotLinked: "Google ilə daxil olanda bağlanır",
    googleSoon: "Tezliklə",
    plan: "Aylıq abunə",
    noSub: "Pulsuz plan",
    noSubText: "Abunə yoxdur. Açıqdır: statistika və hər mövzudan 1 günün sualı.",
    subscribe: "Abunə ol",
    noPayments: "Hələ ödəniş yoxdur.",
    active: "Aktiv",
    canceled: "Ləğv edilib",
    nextPayment: "Növbəti ödəniş",
    accessUntil: "Giriş qalır",
    amount: "Məbləğ",
    method: "Üsul",
    changeMethod: "Üsulu dəyiş",
    cancel: "Abunəni ləğv et",
    resume: "Abunəni bərpa et",
    logout: "Çıxış",
    meta: (username: string | null, grade: number | null, target: string) =>
      [username ? `@${username}` : null, grade ? `${grade}-ci sinif` : null, target].filter(Boolean).join(" · "),
  },
  cancel: {
    title: "Abunəni ləğv edək?",
    text: "Abunə dərhal dayanır və Free plana keçirsən. Bundan sonra:",
    lose: "Günün suallarının çoxu, həftəlik sınaq və planın digər imkanları bağlanır",
    keep1: "Proqresin və streak tarixçən saxlanır",
    keep2: "Alınmış sınaqlar səndə qalır",
    reason: "Səbəb",
    optional: "(istəyə bağlı)",
    reasons: ["Bahadır", "İmtahan bitdi", "Vaxtım yoxdur", "Digər"],
    stay: "Abunədə qal",
    confirm: "Bəli, ləğv et",
    doneTitle: "Abunə ləğv edildi",
    doneText: "Free plana keçdin. Proqresin və alınmış sınaqların saxlanılır. Fikrini dəyişsən, abunəni bərpa edə bilərsən.",
    toPanel: "Panelə qayıt",
    undo: "Fikrimi dəyişdim — bərpa et",
  },
  plans: {
    title: "Abunəliklər",
    lead: "Hər daxil olan istifadəçi Free plandadır. Lazım olanda Pro və ya Premium-a keç — istədiyin vaxt ləğv edə bilərsən.",
    choose: (name: string) => `${name}-${/[aeıioöuü]$/i.test(name) ? "ya" : "a"} keç`,
    manage: "Abunəni idarə et",
    activeUntil: (date: string) => `Növbəti ödəniş: ${date}`,
    examPrice: (price: string) => `Plandan əlavə tək sınaq almaq da olar — ${price}.`,
    free: "Pulsuz",
  },
  payment: {
    title: "Ödəniş",
    selected: "Seçilmiş plan",
    change: "Dəyiş",
    monthly: "Aylıq abunə",
    monthlyNote: "Hər ay avtomatik yenilənir",
    planLabel: "Plan seç",
    planTitle: (name: string) => `${name} · aylıq abunə`,
    planFeatures: {
      free: ["Günün hər mövzusundan 2 sual", "Səhvlərim", "Statistika", "Ayda 1 pulsuz sınaq (özün seçirsən)"],
      pro: ["Günün bütün sualları", "Səhvlərim + oxşar suallar", "Statistika", "Həftədə 1 sınaq (özün seçirsən)"],
      premium: ["Pro-dakı hər şey", "Bütün sınaqlar", "Onlayn repetitor"],
    },
    current: "Cari plan",
    perMonth: (p: string) => `${p} / ay`,
    examNote: "Bir dəfəlik alış, hesabında qalır",
    method: "Ödəniş üsulu",
    methods: [
      { id: "card", title: "Bank kartı", sub: "Visa, Mastercard və yerli kartlar" },
      { id: "local", title: "Yerli ödəniş üsulu", sub: "[Üsul adı — provayder sonra seçiləcək]" },
      { id: "other", title: "Digər üsul", sub: "[Yer tutucu]" },
    ],
    providerPlaceholder: "Ödəniş provayderinin kart forması (iframe / yönləndirmə — yer tutucu)",
    discount: "Endirim",
    total: "Cəmi",
    consentMonthly: "Abunənin hər ay avtomatik yenilənməsi ilə razıyam.",
    consentExam: "Alış şərtləri ilə razıyam.",
    consentRequired: "Davam etmək üçün razılığı təsdiqlə.",
    refund: "Geri qaytarma siyasəti",
    pay: (p: string) => `${p} ödə`,
    safe: "Kart məlumatları bizdə saxlanmır.",
    demoFail: "Demo: uğursuz ödənişi göstər",
    mockNote: "Demo rejimi: real ödəniş yoxdur, düymə ödənişi təqlid edir.",
    okTitle: "Ödəniş uğurludur",
    okTextMonthly: "Abunən aktivdir. Günün sualları artıq hazırdır.",
    okTextExam: "Sınaq hesabına əlavə olundu. İstədiyin vaxt başla.",
    receipt: "Elektron qəbz",
    paid: "Ödənilib",
    receiptNo: "Qəbz №",
    date: "Tarix",
    plan: "Plan",
    period: "Müddət",
    print: "Çap et / PDF",
    toDaily: "Günün suallarına keç",
    toExam: "Sınağa başla",
    copySent: (email: string) => `Qəbzin surəti ${email} ünvanına göndərildi.`,
    failTitle: "Ödəniş keçmədi",
    failText: "Kartdan pul çıxılmayıb. Narahat olma — yenidən cəhd et.",
    failReason: "Səbəb: bank əməliyyatı rədd etdi",
    failHint: "Kartda kifayət qədər vəsait olduğunu və onlayn ödənişin açıq olduğunu yoxla.",
    retry: "Yenidən cəhd et",
    otherMethod: "Başqa üsul seç",
    support: "Problem qalırsa:",
    supportLink: "Telegram-da yaz",
  },
  stats: {
    title: "Statistika",
    h1: "İmtahan statistikası",
    intro:
      "Keçmiş DİM riyaziyyat imtahanlarının sualları mövzulara bölünüb və test topluları ilə tutuşdurulub.",
    login: "Daxil ol",
    register: "Qeydiyyat",
    filters: {
      label: "Süzgəclər",
      kind: "İmtahan növü",
      kinds: { all: "Hamısı", buraxilis: "Buraxılış", qebul: "Qəbul" },
      group: "Qrup",
      allGroups: "Bütün qruplar",
      groupOpt: (g: string) => `${g} qrup`,
      years: "İllər",
      yearsHint: "Heç biri seçilməyibsə — bütün illər.",
      reset: "Süzgəcləri sıfırla",
      updating: "Yenilənir…",
      kindsValue: "Buraxılış və qəbul",
      yearsValue: "2016–2026",
    },
    cards: {
      questions: "Analiz olunmuş sual",
      exams: "Analiz olunmuş imtahan",
      topics: "Mövzu",
      match: "Test toplularında qarşılığı tapılıb",
    },
    ranking: {
      title: "Mövzular reytinqi",
      subtitle: "Ən çox çıxan mövzudan başlayaraq. Mövzuya klikləyin — ətraflı səhifə açılır.",
      summary: (name: string, n: string, pct: string) => `Ən çox çıxan mövzu: ${name}, ${n} sual, ${pct}`,
      value: (n: string, pct: string) => `${n} sual · ${pct}`,
      personal: (pct: string, ok: number, total: number) => `Sənin nəticən: ${pct} (${ok}/${total})`,
      personalNote: "Nöqtə — sənin düzgün cavab faizin (günün sualları və sınaqlar üzrə, 0–100%).",
      caption: "Mövzular üzrə imtahanda çıxan sual sayı",
      colTopic: "Mövzu",
      colCount: "Sual sayı",
      colShare: "Payı",
      colPersonal: "Sənin nəticən",
    },
    perExam: {
      title: "Hər imtahanda neçə tapşırıq",
      titleKind: (k: string) => `Hər ${k} imtahanında neçə tapşırıq`,
      caption: (n: string) => `Mövzu üzrə imtahan başına tapşırıq sayı (${n} imtahan əsasında)`,
      colTopic: "Mövzu",
      colAvg: "Orta",
      colRange: "Ən az – ən çox",
    },
    plan: {
      title: "Prioritet plan",
      badge: "Abunə",
      subtitle: "Əvvəl bunları işlə. Bal = mövzunun imtahanda çıxma payı × (1 − sənin düzgün faizin).",
      noData: "Bir sınaq və ya 10 günün sualı həll et, plan hazırlansın.",
      lockedTitle: "Prioritet plan abunə ilə açılır",
      lockedText: "Sənin nəticələrinə görə ilk 5 mövzu və hər biri üçün toplu səhifələri.",
      subscribe: "Abunə ol",
      loginText: "Planı görmək üçün daxil ol.",
      score: (share: string, pct: string) => `Payı ${share} · sənin nəticən ${pct}`,
      refs: "Toplu səhifələri:",
      noRefs: "Bu mövzu üzrə toplu istinadı yoxdur.",
      more: "Mövzunun bütün istinadları",
    },
    table: { show: "Cədvəl kimi göstər", chart: "Qrafik kimi göstər" },
    empty: { title: "Bu seçim üçün məlumat yoxdur", text: "Süzgəcləri dəyişin və ya sıfırlayın." },
    error: { title: "Statistika yüklənmədi", text: "Bağlantıda problem oldu. Bir az sonra yenidən cəhd edin.", retry: "Yenidən cəhd et" },
    method: { title: "Metodika və qeydlər" },
    detail: {
      back: "Bütün mövzular",
      cards: { total: "Cəmi sual", share: "Bütün sualların payı", avg: "İmtahan başına orta", match: "Test toplularında qarşılığı" },
      years: "İllər üzrə dinamika",
      yearsSummary: (pairs: string) => `İllər üzrə sual sayı: ${pairs}`,
      yearsCaption: "İllər üzrə sual sayı",
      kinds: "Buraxılış və qəbul",
      kindsSummary: (b: string, q: string) => `Buraxılış: ${b} sual, qəbul: ${q} sual`,
      kindsCaption: "İmtahan növü üzrə sual sayı",
      kind: { buraxilis: "Buraxılış", qebul: "Qəbul" },
      matches: "Test toplusu ilə uyğunluq dərəcələri",
      matchesSummaryAll: (pairs: string) => `Test toplusu ilə uyğunluq: ${pairs}`,
      matchesCaptionAll: "Test toplusu ilə uyğunluq dərəcələri (faizlə)",
      colShare: "Payı",
      matchesSummary: (toplu: string, pairs: string) => `${toplu} toplu: ${pairs}`,
      matchesCaption: (toplu: string) => `${toplu} toplu ilə uyğunluq dərəcələri`,
      toplu: (y: string) => `${y} toplu`,
      colLevel: "Dərəcə",
      colCount: "Sual sayı",
      colYear: "İl",
      colKind: "Növ",
      types: "Sual tipləri",
      typesMore: (n: number) => `Bütün tiplər (${n})`,
      colType: "Tip",
      refs: "Toplu istinadları",
      refsNote: "Nümunə: mövzu üzrə yalnız 10 istinad göstərilir. Yalnız istinad — kitab, hissə, səhifə və nömrə; sualın mətni göstərilmir.",
      colToplu: "Test toplusu",
      sample: "Nümunə",
      refsCaption: "Toplu istinadları",
      colExam: "İmtahan",
      colNo: "Sual №",
      col2023: "2023 toplu",
      col2025: "2025 toplu",
      none: "—",
    },
  },
} as const;
