// Landing səhifəsinin mətnləri (az.ts → az.landing).

export const azLanding = {
  meta: {
    title: "DİM riyaziyyat imtahanlarına statistik hazırlıq",
    description:
      "Keçmiş DİM imtahan sualları mövzu və tiplərə bölünüb: hər tipin neçə dəfə çıxdığını və test toplusunun hansı səhifəsində olduğunu gör.",
  },
  nav: {
    label: "Əsas",
    topics: "Mövzular",
    how: "Necə işləyir",
    exams: "Sınaqlar",
    pricing: "Qiymətlər",
    login: "Daxil ol",
    telegram: "Telegram",
    signup: "Pulsuz başla",
    menu: "Menyu",
    close: "Menyunu bağla",
  },
  hero: {
    eyebrow: "DİM buraxılış və qəbul · 9–11-ci sinif",
    titleA: "İmtahanda nə çıxıb,",
    titleB: "nəyi işləməlisən",
    lead: "Keçmiş imtahan sualları tiplərə bölünüb. Hər tipin neçə dəfə çıxdığını və toplunun hansı səhifəsində olduğunu gör.",
    telegram: "Telegram kanala qoşul",
    signup: "Pulsuz başla",
    sample: "Nümunə kartına bax",
    note: "Pulsuz statistika · Qeydiyyatsız baxmaq olar",
    stats: "Statistikaya bax",
    rankEyebrow: "Canlı statistika",
    rankTitle: "Ən çox sual çıxan mövzular",
    rankNote: (n: string, years: string) => `${n} sual · ${years}`,
    rankLink: "Bütün mövzuların reytinqi",
  },
  sample: {
    aria: "Nümunə tapşırıq kartı",
    topic: "Faiz və nisbət",
    freq: "İmtahanda çıxıb: 2 dəfə",
    typeLabel: "Tip",
    type: "Ardıcıl faiz artımı və azalması",
    ref: "2025 toplu, I hissə, səh.146 №11",
    choose: "Sualı kitabda həll et, cavabını seç:",
    answers: "Cavab variantları",
    answer: (l: string) => `Cavab ${l}`,
    method: "Həll metodu",
    formula: "$x \\cdot \\left(1 + \\frac{p}{100}\\right) \\cdot \\left(1 - \\frac{q}{100}\\right)$",
    methodText: "Hər dəyişiklik əvvəlki qiymətə tətbiq olunur. Faizləri toplama — vur.",
    picked: (l: string) => `Seçdin: ${l}.`,
    pickedCta: "Cavabı yoxlamaq və həlli görmək üçün pulsuz qeydiyyatdan keç",
  },
  stats: {
    eyebrow: "Rəqəmlərlə",
    title: "Təxmin yox, statistika",
    questions: "imtahan sualı analiz olunub",
    years: (list: string) => `imtahan: ${list}`,
    topics: "mövzu üzrə təsnifat",
    found: "sualın qarşılığı test toplularında tapılıb",
  },
  how: {
    eyebrow: "3 addım",
    title: "Necə işləyir",
    steps: [
      { title: "Mövzunu seç", text: (n: string) => `${n} mövzudan birini aç: məsələn, “Faiz. Nisbət. Tənasüb”.` },
      { title: "Tipləri gör", text: () => "Hər tipin imtahanda neçə dəfə çıxdığını rəqəmlə gör." },
      { title: "Səhifəni öyrən", text: () => "Toplunun hansı hissəsi, səhifəsi və nömrəsi — dəqiq." },
    ],
  },
  card: {
    eyebrow: "Nümunə kart",
    title: "Bir tip — bir kart",
    lead: "Sualın mətni kitabdadır. Kartda istinad, cavab seçimi və həll metodu var.",
    features: ["Toplu, hissə, səhifə və nömrə", "İmtahanda neçə dəfə çıxıb", "Qısa həll metodu"],
  },
  topics: {
    eyebrow: "Mövzular",
    title: (n: string) => `${n} mövzu, hər biri rəqəmlə`,
    lead: "Ən çox sual çıxan mövzulardan başla.",
    count: "sual çıxıb",
    all: (n: string) => `Bütün ${n} mövzunu gör`,
  },
  exams: {
    eyebrow: "Sınaq imtahanları",
    title: "Real formatda yoxla",
    lead: "İmtahan şəraitində həll et. Sonra mövzular üzrə nəticəni və həll izahlarını gör.",
    cta: "Sınaqlara bax",
    card: "Buraxılış sınağı",
    questions: (n: number) => `${n} sual`,
    closed: "qapalı (A–E)",
    coded: "kodlaşdırılan",
    written: "yazılı (açıq)",
    formatLabel: (c: number, k: number, w: number) => `${c} qapalı, ${k} kodlaşdırılan, ${w} yazılı`,
    features: ["Vaxt sayğacı və cavab vərəqi", "Hər sualın həll izahı", "Zəif tiplər üçün toplu istinadı"],
  },
  pricing: {
    eyebrow: "Qiymətlər",
    title: "Pulsuz başla, lazım olanda aç",
    lead: "Hər daxil olan istifadəçi Free plandadır. Gündəlik məşq üçün Pro, hər şey üçün Premium. Tək sınaq — 3 AZN.",
    popular: "Ən çox seçilən",
    notIncluded: "daxil deyil",
    plans: {
      free: {
        name: "Free",
        price: "0 AZN",
        unit: "",
        cta: "Pulsuz başla",
        features: [
          { text: "Günün sualları: hər mövzudan 2 sual", on: true },
          { text: "Səhvlərim", on: true },
          { text: "Statistika", on: true },
          { text: "Ayda 1 pulsuz sınaq (özün seçirsən)", on: true },
          { text: "Onlayn repetitor", on: false },
        ],
      },
      monthly: {
        name: "Pro",
        price: "6.90 AZN",
        unit: "/ ay",
        cta: "Pro-ya keç",
        note: "İstədiyin vaxt ləğv et",
        features: [
          { text: "Günün bütün sualları: hər gün 4 mövzu × 5 sual", on: true },
          { text: "Səhvlərim + oxşar suallar", on: true },
          { text: "Statistika", on: true },
          { text: "Həftədə 1 sınaq (özün seçirsən)", on: true },
          { text: "Onlayn repetitor", on: false },
        ],
      },
      exam: {
        name: "Premium",
        price: "12.90 AZN",
        unit: "/ ay",
        cta: "Premium-a keç",
        features: [
          { text: "Pro-dakı hər şey", on: true },
          { text: "Bütün sınaqlar", on: true },
          { text: "Onlayn repetitor: həftəlik qrafik, nəzəriyyə və testlər", on: true },
          { text: "Hər 2 mövzudan sonra 20 suallıq sınaq", on: true },
        ],
      },
    },
  },
  teacher: {
    eyebrow: "Müəllim",
    photo: "Müəllim şəkli",
    name: "[Müəllimin adı]",
    years: "[X] il riyaziyyat müəllimi",
    quote: "“Şagird hər şeyi işləməli deyil. İmtahanda nə çıxdığını bilsə, vaxtını düz bölər.”",
    bio: "[Qısa tanıtım mətni: təcrübə, yanaşma, niyə bu layihə yaradılıb — 2–3 cümlə.]",
    results: "Şagirdlərin nəticələri",
    resultCard: "Nəticə kartı (bal, il)",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Tez-tez verilən suallar",
    items: [
      {
        q: "Bu sayt DİM-in saytıdır?",
        a: "Xeyr. Layihə müstəqildir və DİM ilə əlaqəli deyil. Biz açıq imtahan suallarını özümüz təhlil edirik.",
      },
      {
        q: "Sualların mətni haradadır?",
        a: "Sualların mətni test toplularındadır. Kartda toplu, hissə, səhifə və nömrə göstərilir — kitabı açıb həll edirsən.",
      },
      {
        q: "Hazırlığa nə qədər vaxt lazımdır?",
        a: "Gündə 20–30 dəqiqə ilə başla. Əvvəl ən çox çıxan tiplərə fokuslan, sonra zəif mövzulara keç.",
      },
      {
        q: "Hansı toplular lazımdır?",
        a: "DİM-in 2023 və 2025 test topluları (I və II hissə). Hər sual üçün hər iki toplunun səhifə və nömrəsi göstərilir.",
      },
    ],
  },
  cta: {
    title: "Hər gün bir addım",
    text: "Telegram-da gündəlik statistika və yeni kartlar. Instagram-da qısa izahlar.",
    telegram: "Telegram kanala qoşul",
    instagram: "Instagram",
    // Sosial linklər hələ verilməyibsə (NEXT_PUBLIC_TELEGRAM_URL / NEXT_PUBLIC_INSTAGRAM_URL)
    altText: "Pulsuz qeydiyyatdan keç: statistika, günün sualları və sınaqlar bir yerdə.",
    signup: "Pulsuz başla",
    stats: "Statistikaya bax",
  },
  footer: {
    tagline: "İmtahanda nə çıxıb, nəyi işləməlisən — rəqəmlərlə.",
    site: "Sayt",
    legal: "Hüquqi",
    links: { topics: "Mövzular", stats: "Statistika", exams: "Sınaqlar", pricing: "Qiymətlər", login: "Daxil ol" },
    legalLinks: { terms: "İstifadə şərtləri", privacy: "Məxfilik siyasəti", refund: "Geri qaytarma siyasəti" },
    note: "Sualların mətni test toplularına aiddir; saytda yalnız istinad göstərilir.",
  },
} as const;
