// Bütün interfeys mətnləri. Başqa dil əlavə olunanda bu faylın strukturu təkrarlanacaq.
import { brand } from "@/config/brand";
import { azApp } from "./az-app";
import { azLanding } from "./az-landing";

export const az = {
  app: azApp,
  landing: azLanding,
  common: {
    homeSuffix: " — ana səhifə",
    independence: "Bu layihə müstəqildir və DİM ilə əlaqəli deyil.",
    copyright: `© ${brand.year} ${brand.name}`,
    or: "və ya",
    orEmail: "və ya e-poçtla",
    loading: "Gözlə…",
    showPassword: "Şifrəni göstər",
    hidePassword: "Şifrəni gizlət",
  },
  legalLinks: {
    terms: "İstifadə şərtləri",
    privacy: "Məxfilik siyasəti",
    refund: "Geri qaytarma",
  },
  authAside: {
    tags: (questions: string, topics: string, pct: string) => [`${questions} sual`, `${topics} mövzu`, `${pct} toplularda`],
    login: {
      title: "Xoş gəldin!",
      text: "Statistikan, günün sualları və sınaqların bir yerdə.",
    },
    register: {
      title: "Hazırlığı rəqəmlərlə qur",
      text: "Qeydiyyat pulsuzdur. Statistika və mövzu siyahıları dərhal açılır.",
    },
  },
  login: {
    metaTitle: "Daxil ol",
    title: "Daxil ol",
    subtitle: "Hesabına daxil ol və qaldığın yerdən davam et.",
    google: "Google ilə davam et",
    identifier: "E-poçt və ya istifadəçi adı",
    password: "Şifrə",
    forgot: "Şifrəni unutdum",
    submit: "Daxil ol",
    noAccount: "Hesabın yoxdur?",
    register: "Qeydiyyatdan keç",
    newUserPrefix: "Yeni istifadəçisən?",
    newUserSuffix: "— 1 dəqiqə çəkir.",
    resetDone: "Şifrən yeniləndi. Yeni şifrə ilə daxil ol.",
    verifiedDone: "E-poçtun təsdiqləndi. İndi daxil ol.",
  },
  register: {
    metaTitle: "Qeydiyyat",
    step: (n: number, total: number) => `Addım ${n} / ${total} · Hesab`,
    title: "Qeydiyyat",
    google: "Google ilə qeydiyyatdan keç",
    name: "Ad",
    username: "İstifadəçi adı",
    usernameHint: "Hərf, rəqəm və “_”. Başqaları görəcək.",
    email: "E-poçt",
    password: "Şifrə",
    strengthLabel: "Şifrənin gücü",
    strength: ["Çox zəif", "Zəif", "Orta", "Yaxşı", "Güclü"],
    reqs: {
      length: "Ən azı 8 simvol",
      cases: "Böyük və kiçik hərf",
      digit: "Ən azı 1 rəqəm",
      symbol: "Simvol (!, ?, #) — tövsiyə",
    },
    grade: "Sinif",
    target: "Hədəf imtahan",
    targets: { buraxilis: "Buraxılış", qebul: "Qəbul", both: "Hər ikisi" },
    termsAnd: "və",
    termsPrivacy: "məxfilik siyasəti",
    termsAfter: "ilə razıyam",
    emailTakenPrefix: "Bu sənin hesabındırsa,",
    emailTakenLogin: "daxil ol",
    emailTakenOr: "və ya",
    emailTakenReset: "şifrəni bərpa et",
    submit: "Davam et",
    hasAccount: "Hesabın var?",
    login: "Daxil ol",
  },
  verify: {
    metaTitle: "Poçtunu yoxla",
    title: "Poçtunu yoxla",
    sentTo: "ünvanına təsdiq linki göndərdik. Linkə kliklə — hesab aktiv olacaq.",
    sentGeneric: "E-poçtuna təsdiq linki göndərdik. Linkə kliklə — hesab aktiv olacaq.",
    openMail: "Poçtu aç",
    resend: "Yenidən göndər",
    resent: "Link yenidən göndərildi.",
    noMailPrefix: "Məktub gəlmədi? “Spam” qovluğuna bax və ya",
    changeEmail: "e-poçtu dəyiş",
    okTitle: "E-poçt təsdiqləndi",
    okText: "Hesabın aktivdir. İndi daxil ola bilərsən.",
    okCta: "Daxil ol",
    expiredTitle: "Linkin vaxtı bitib",
    expiredText: "Təhlükəsizlik üçün link 24 saat işləyir. Daxil olmağa cəhd et — yeni link göndərəcəyik.",
    invalidTitle: "Link işləmir",
    invalidText: "Link yanlışdır və ya artıq istifadə olunub. Hesabın təsdiqlənibsə, sadəcə daxil ol.",
    toLogin: "Girişə qayıt",
  },
  forgot: {
    metaTitle: "Şifrə bərpası",
    title: "Şifrəni bərpa et",
    subtitle: "Hesabının e-poçtunu yaz — şifrəni yeniləmək üçün link göndərəcəyik.",
    email: "E-poçt",
    submit: "Link göndər",
    sentTitle: "Poçtunu yoxla",
    sentText: "Bu e-poçtla hesab varsa, şifrə bərpası linki göndərdik. Link 30 dəqiqə işləyir.",
    back: "Girişə qayıt",
  },
  reset: {
    metaTitle: "Yeni şifrə",
    title: "Yeni şifrə",
    subtitle: "Yeni şifrəni yaz. Köhnə şifrə artıq işləməyəcək.",
    password: "Yeni şifrə",
    submit: "Şifrəni yenilə",
    invalidTitle: "Link işləmir",
    invalidText: "Link yanlışdır, vaxtı bitib və ya artıq istifadə olunub. Yeni link istə.",
    again: "Yeni link istə",
  },
  panel: {
    metaTitle: "Panel",
    hello: (name: string) => `Salam, ${name}!`,
    placeholder: "Panel növbəti mərhələdə hazırlanacaq. Giriş işləyir.",
    logout: "Çıxış",
  },
  legal: {
    updated: "Son yenilənmə: [TARİX]",
    placeholder: "[Mətn yer tutucudur — hüquqşünas tərəfindən yazılacaq.]",
  },
  errors: {
    required: "Bu sahəni doldur.",
    nameRequired: "Adını yaz.",
    nameTooLong: "Ad 60 simvoldan uzun olmasın.",
    emailInvalid: "E-poçt düzgün deyil. Məs.: ad@mail.az",
    usernameInvalid: "3–20 simvol: kiçik hərf, rəqəm və “_”.",
    usernameTaken: "Bu istifadəçi adı tutulub. Başqasını seç.",
    emailTaken: "Bu e-poçtla hesab var.",
    passwordShort: "Şifrə ən azı 8 simvol olsun.",
    passwordLong: "Şifrə 128 simvoldan uzun olmasın.",
    passwordWeak: "Şifrədə böyük və kiçik hərf, bir də rəqəm olsun.",
    gradeRequired: "Sinfini seç.",
    targetRequired: "Hədəf imtahanı seç.",
    termsRequired: "Davam etmək üçün şərtlərlə razılaş.",
    wrongPassword: "Şifrə yanlışdır. Yenidən yoxla.",
    notFoundEmail: "Bu e-poçtla hesab tapılmadı.",
    notFoundUsername: "Bu istifadəçi adı ilə hesab tapılmadı.",
    googleOnly: "Bu hesab Google ilə yaradılıb. “Google ilə davam et” düyməsini seç və ya şifrə bərpası ilə şifrə qoy.",
    unverified: "E-poçtun hələ təsdiqlənməyib. Poçtuna yeni link göndərdik.",
    unverifiedCta: "Təsdiq səhifəsinə keç",
    rateLimited: (minutes: number) =>
      `Çox cəhd oldu. ${minutes} dəqiqə sonra yenidən yoxla.`,
    resendWait: (seconds: number) => `${seconds} saniyə sonra yenidən göndərə bilərsən.`,
    captcha: "Yoxlama keçmədi. Səhifəni yenilə və yenidən cəhd et.",
    generic: "Nəsə alınmadı. Bir az sonra yenidən cəhd et.",
  },
  email: {
    verifySubject: `${brand.name}: e-poçtunu təsdiqlə`,
    verifyText: (name: string, url: string) =>
      `Salam, ${name}!\n\nHesabını aktiv etmək üçün linkə kliklə:\n${url}\n\nLink 24 saat işləyir. Qeydiyyatdan keçməmisənsə, bu məktubu nəzərə alma.`,
    resetSubject: `${brand.name}: şifrə bərpası`,
    resetText: (name: string, url: string) =>
      `Salam, ${name}!\n\nŞifrəni yeniləmək üçün linkə kliklə:\n${url}\n\nLink 30 dəqiqə işləyir və bir dəfə istifadə olunur. Bunu sən istəməmisənsə, heç nə etmə — şifrən dəyişməyəcək.`,
  },
} as const;
